/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ownermodules;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

import auth.AuthFunctions;
import auth.LoginPage;
import models.User;
import storage.StorageFunctions;
import validations.Validation;

/**
 *
 * @author adolf
 */
public class OwnerDashboard extends javax.swing.JFrame {
    public User user;
    // public int fleetNumber;
    // public int activeRentals;
    // public int totalCarOwnerRevenue;

    /**
     * Creates new form OwnerDashboard
     */
    public OwnerDashboard(User user) throws UnsupportedLookAndFeelException {
        // Set Nimbus look and feel
        // try {
        //     for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        //         if ("Nimbus".equals(info.getName())) {
        //             UIManager.setLookAndFeel(info.getClassName());
        //             break;
        //         }
        //     }
        // } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        //     e.printStackTrace();  // Handle any exceptions
        // }
        this.user = user;
        initComponents();

        this.setTitle("Owner Dashboard");

        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        /* Dynamic data */
        /* User data */
        try {

            String carDetailsPath = "src\\storage\\cars.csv";
            // System.out.println(user.getEmail());
            int fleetNumber = StorageFunctions.countCarsByOwnerEmail(user.getEmail());
            lblTotalFleetNumber.setText(""+ fleetNumber); // display number of vehicles in the fleet

            
            int activeRentals = StorageFunctions.countActiveRentals(carDetailsPath, user.getEmail()); 

            lblActiveRentals.setText(""+ activeRentals); // display current 'active' rentals


            double totalCarOwnerRevenue = StorageFunctions.calculateOwnerRevenue(user.getEmail()); 
            lblRevenue.setText("N$ "+ totalCarOwnerRevenue); // display the amount of revenue

           
        } catch (FileNotFoundException e) {
            System.out.println("File not found: " + e.getMessage());
        }

        lblFirstNameDynamic.setText(user.getFirstName() + " " + user.getLastName());

        lblUserTypeDynamic.setText(user.getUserType()); // display user type


        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        lblManageFleet = new javax.swing.JLabel();
        lblAddCar = new javax.swing.JLabel();
        lblBookedCars = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblUserTypeDynamic = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblFirstNameDynamic = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookingHistory = new javax.swing.JTable();
        lblBookingHistoryTitle = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblActiveRentalsTitle = new javax.swing.JLabel();
        lblActiveRentals = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblTotalFleetNumberTitle = new javax.swing.JLabel();
        lblTotalFleetNumber = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblRevenueTitle = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lblEditProfileTitle = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textPhoneNumber = new javax.swing.JTextField();
        btnEditPersonalInformation = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(237, 223, 205));
        jPanel1.setForeground(new java.awt.Color(217, 186, 164));

        jPanel2.setBackground(new java.awt.Color(217, 186, 164));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 62, 52));
        jLabel1.setText("Leenda");

        lblDashboard.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(133, 62, 52));
        lblDashboard.setText("Dashboard");

        btnLogOut.setBackground(new java.awt.Color(237, 233, 205));
        btnLogOut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(133, 62, 52));
        btnLogOut.setText("Log Out");
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblManageFleet.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblManageFleet.setForeground(new java.awt.Color(133, 62, 52));
        lblManageFleet.setText("Manage Fleet");
        lblManageFleet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageFleetMouseClicked(evt);
            }
        });

        lblAddCar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAddCar.setForeground(new java.awt.Color(133, 62, 52));
        lblAddCar.setText("Add Car");
        lblAddCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    lblAddCarMouseClicked(evt);
                } catch (UnsupportedLookAndFeelException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        lblBookedCars.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBookedCars.setForeground(new java.awt.Color(133, 62, 52));
        lblBookedCars.setText("Booked Cars");
        lblBookedCars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookedCarsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(259, 259, 259)
                .addComponent(lblDashboard)
                .addGap(18, 18, 18)
                .addComponent(lblManageFleet)
                .addGap(18, 18, 18)
                .addComponent(lblBookedCars)
                .addGap(18, 18, 18)
                .addComponent(lblAddCar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDashboard)
                    .addComponent(lblManageFleet)
                    .addComponent(lblAddCar)
                    .addComponent(lblBookedCars)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(133, 62, 52));
        jLabel3.setText("Dashboard");

        jPanel5.setBackground(new java.awt.Color(217, 186, 164));
        jPanel5.setForeground(new java.awt.Color(217, 186, 164));

        lblUserTypeDynamic.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblUserTypeDynamic.setForeground(new java.awt.Color(133, 62, 52));
        lblUserTypeDynamic.setText("Car Owner");
        lblUserTypeDynamic.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-88 (2).png"))); // NOI18N

        lblFirstNameDynamic.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblFirstNameDynamic.setForeground(new java.awt.Color(133, 62, 52));
        lblFirstNameDynamic.setText("Adolf David");
        lblFirstNameDynamic.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFirstNameDynamic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserTypeDynamic)
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserTypeDynamic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFirstNameDynamic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(217, 186, 164));

        tblBookingHistory.setBackground(new java.awt.Color(237, 223, 205));
        tblBookingHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Car Name", "Total Revenue", "Days Rented Out", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(tblBookingHistory);

        lblBookingHistoryTitle.setBackground(new java.awt.Color(217, 186, 164));
        lblBookingHistoryTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblBookingHistoryTitle.setForeground(new java.awt.Color(133, 62, 52));
        lblBookingHistoryTitle.setText("Booking History");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBookingHistoryTitle)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBookingHistoryTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(217, 186, 164));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(217, 186, 164));
        jPanel12.setPreferredSize(new java.awt.Dimension(350, 118));

        lblActiveRentalsTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblActiveRentalsTitle.setForeground(new java.awt.Color(133, 62, 52));
        lblActiveRentalsTitle.setText("Active Rentals");

        lblActiveRentals.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblActiveRentals.setForeground(new java.awt.Color(133, 62, 52));
        lblActiveRentals.setText("5");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cars-85.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel16))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActiveRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblActiveRentalsTitle))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblActiveRentalsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblActiveRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(20, 20, 20)
                .addComponent(jLabel16))
        );

        jPanel14.setBackground(new java.awt.Color(217, 186, 164));
        jPanel14.setPreferredSize(new java.awt.Dimension(350, 118));

        lblTotalFleetNumberTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTotalFleetNumberTitle.setForeground(new java.awt.Color(133, 62, 52));
        lblTotalFleetNumberTitle.setText("Total Fleet Number");

        lblTotalFleetNumber.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblTotalFleetNumber.setForeground(new java.awt.Color(133, 62, 52));
        lblTotalFleetNumber.setText("4");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/garadge-icon.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(217, 186, 164));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalFleetNumberTitle)
                            .addComponent(lblTotalFleetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTotalFleetNumberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalFleetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22))
                .addGap(32, 32, 32)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel15.setBackground(new java.awt.Color(217, 186, 164));
        jPanel15.setPreferredSize(new java.awt.Dimension(350, 118));

        lblRevenueTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblRevenueTitle.setForeground(new java.awt.Color(133, 62, 52));
        lblRevenueTitle.setText("Revenue");

        lblRevenue.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblRevenue.setForeground(new java.awt.Color(133, 62, 52));
        lblRevenue.setText("NAD 69420");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-payment-history-88.png"))); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(lblRevenueTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblRevenueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(217, 186, 164));

        lblEditProfileTitle.setBackground(new java.awt.Color(217, 186, 164));
        lblEditProfileTitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblEditProfileTitle.setForeground(new java.awt.Color(133, 62, 52));
        lblEditProfileTitle.setText("Edit Profile");

        jLabel23.setBackground(new java.awt.Color(133, 62, 52));
        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(133, 62, 52));
        jLabel23.setText("Firstname");

        jLabel24.setBackground(new java.awt.Color(133, 62, 52));
        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(133, 62, 52));
        jLabel24.setText("Lastname");

        jLabel25.setBackground(new java.awt.Color(133, 62, 52));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(133, 62, 52));
        jLabel25.setText("Email");

        jLabel26.setBackground(new java.awt.Color(133, 62, 52));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(133, 62, 52));
        jLabel26.setText("Phone Number");

        textFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });

        textLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPerformed(evt);
            }
        });

        btnEditPersonalInformation.setBackground(new java.awt.Color(133, 62, 52));
        btnEditPersonalInformation.setText("Edit Profile");
        btnEditPersonalInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnEditPersonalInformationActionPerformed(evt);
                } catch (UnsupportedLookAndFeelException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblEditProfileTitle))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEditPersonalInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFirstName)
                            .addComponent(jLabel25)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24)
                            .addComponent(textLastName)
                            .addComponent(jLabel26)
                            .addComponent(textPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditProfileTitle)
                .addGap(25, 25, 25)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEditPersonalInformation)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnLogoutOnClick(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnLogoutOnClick
        this.dispose();
        new LoginPage();
    }// GEN-LAST:event_btnLogoutOnClick




        private void btnEditPersonalInformationActionPerformed(java.awt.event.ActionEvent evt) throws UnsupportedLookAndFeelException{// GEN-FIRST:event_btnEditUsersPersonalInformationOnClick
        String userID = user.getUserID().trim();
        String firstName = textFirstName.getText().trim();
        String lastName = textLastName.getText().trim();
        String email = textEmail.getText().trim();
        String phoneNumber = textPhoneNumber.getText().trim();
        //String driverLicense = textDriversLicense.getText().trim();

        // Check if the user ID is empty
        if (Validation.checkIfTheTextFieldIsEmpty(userID, "user ID")) {
            return; // Exit if user ID is empty
        }

        // Counter for filled fields
        int filledFieldCount = 0;

        // Validate first name if it's not empty
        if (!firstName.isEmpty()) {
            if (Validation.validateName(firstName)) {
                filledFieldCount++; // Increment only if the name is valid
            } else {
                JOptionPane.showMessageDialog(this, "Invalid first name.", "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Validate last name if it's not empty
        if (!lastName.isEmpty()) {
            if (Validation.validateName(lastName)) {
                filledFieldCount++; // Increment only if the last name is valid
            } else {
                JOptionPane.showMessageDialog(this, "Invalid last name.", "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Validate email if it's not empty
        if (!email.isEmpty()) {
            if (Validation.validateEmail(email)) {
                if (!AuthFunctions.doesEmailExist(email)) {
                    filledFieldCount++; // Increment if the email is valid and doesn't already exist
                } else {
                    JOptionPane.showMessageDialog(this, "Email already exists. Please use a different email.",
                            "Email Exists", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid email address.", "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Validate phone number if it's not empty
        if (!phoneNumber.isEmpty()) {
            if (Validation.validatePhoneNumber(phoneNumber)) {
                filledFieldCount++; // Increment if the phone number is valid
            } else {
                JOptionPane.showMessageDialog(this, "Invalid phone number.", "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Increment the counter for the driver's license if it's filled
        // if (!driverLicense.isEmpty()) {
        //     filledFieldCount++; // No validation needed for driver's license as it's optional
        // }

        // Check if at least one additional field is filled
        if (filledFieldCount == 0) {
            JOptionPane.showMessageDialog(this, "You must fill at least one field other than user ID.",
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit if no other fields are filled
        }

        // Update logic
        final String USER_DETAILS_FILE_PATH = "src/storage/userDetails.csv"; // Path to your user details file

        // Read existing user data
        List<String[]> users = new ArrayList<>();
        boolean userFound = false;

        try (BufferedReader br = new BufferedReader(new FileReader(USER_DETAILS_FILE_PATH))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] userDetails = line.split(",");
                if (userDetails.length < 9)
                    continue; // Adjust based on your actual CSV structure

                // Check if the current user ID matches the one to be updated
                if (userDetails[7].equals(userID)) {
                    userFound = true; // User found

                    // Update fields if they are not empty
                    if (!firstName.isEmpty())
                        userDetails[4] = firstName; // Update first name
                    if (!lastName.isEmpty())
                        userDetails[5] = lastName; // Update last name
                    if (!email.isEmpty())
                        userDetails[0] = email; // Update email
                    if (!phoneNumber.isEmpty())
                        userDetails[2] = phoneNumber; // Update phone number
                    // if (!driverLicense.isEmpty())
                    //     userDetails[6] = driverLicense; // Update driver license
                }
                users.add(userDetails); // Add user data (updated or not) to the list
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading user details: " + e.getMessage(), "File Read Error",
                    JOptionPane.ERROR_MESSAGE);
            return; // Exit on error
        }

        // Check if the user ID was found
        if (!userFound) {
            JOptionPane.showMessageDialog(this, "User ID not found.", "Update Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit if user not found
        }

        // Write updated user data back to the CSV file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(USER_DETAILS_FILE_PATH))) {
            for (String[] user : users) {
                bw.write(String.join(",", user)); // Join fields with commas
                bw.newLine(); // Add a newline after each user record
            }
            JOptionPane.showMessageDialog(this, "User details updated successfully.", "Update Success, Relogin to see changes",
                    JOptionPane.INFORMATION_MESSAGE);
            // Clear input fields
            // No need to clear userID as it is associated with the logged-in user
            textFirstName.setText("");
            textLastName.setText("");
            textEmail.setText("");
            textPhoneNumber.setText("");
            //textDriversLicense.setText("");
            // this.dispose();
            // new OwnerDashboard(user);
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing user details: " + e.getMessage(), "File Write Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnEditPersonalInformationOnClick

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        this.dispose();
        new LoginPage();
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void lblManageFleetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageFleetMouseClicked
        this.dispose();
        new ManageFleet(user);
    }//GEN-LAST:event_lblManageFleetMouseClicked

    private void lblBookedCarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookedCarsMouseClicked
        this.dispose();
        new bookedcars(user);
    }//GEN-LAST:event_lblBookedCarsMouseClicked

    private void lblAddCarMouseClicked(java.awt.event.MouseEvent evt) throws UnsupportedLookAndFeelException {//GEN-FIRST:event_lblAddCarMouseClicked
        this.dispose();
        new AddCar(user);
    }//GEN-LAST:event_lblAddCarMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OwnerDashboard(null).setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(OwnerDashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditPersonalInformation;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActiveRentals;
    private javax.swing.JLabel lblActiveRentalsTitle;
    private javax.swing.JLabel lblAddCar;
    private javax.swing.JLabel lblBookedCars;
    private javax.swing.JLabel lblBookingHistoryTitle;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblEditProfileTitle;
    private javax.swing.JLabel lblFirstNameDynamic;
    private javax.swing.JLabel lblManageFleet;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JLabel lblRevenueTitle;
    private javax.swing.JLabel lblTotalFleetNumber;
    private javax.swing.JLabel lblTotalFleetNumberTitle;
    private javax.swing.JLabel lblUserTypeDynamic;
    private javax.swing.JTable tblBookingHistory;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
