
package adminmodules;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.text.DecimalFormat;

import auth.AuthFunctions;
import auth.LoginPage;
import javax.swing.JOptionPane;

import models.User;
import storage.StorageFunctions;

import java.io.FileNotFoundException;
import java.io.IOException;

public class AdminDashboard extends javax.swing.JFrame {
    public User user;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(User user) {
        // Set Nimbus look and feel
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | UnsupportedLookAndFeelException e) {
            e.printStackTrace(); // Handle any exceptions
        }

        this.setTitle("Dashboard");
        this.user = user;

        initComponents();

        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        /* Dynamic data */
        /* User data */
        try {
            String userDetailsFilePath = "src\\storage\\userDetails.csv";
            int totalUserRecords = StorageFunctions.countRecords(userDetailsFilePath);
            int inactiveUsers = StorageFunctions.countInactiveUsers(userDetailsFilePath);
            lblTotalUsers.setText(String.valueOf(totalUserRecords));
            lblPendingApprovalsTotal.setText(String.valueOf(inactiveUsers));
        } catch (FileNotFoundException e) {
            System.out.println("File not found: " + e.getMessage());
        }

        /* Car data */
        try {
            String carsFilePath = "src\\storage\\cars.csv";
            int totalCarRecords = StorageFunctions.countRecords(carsFilePath);
            int bookedCars = StorageFunctions.countBookedCars(carsFilePath);
            lblNumberOfCarsTotal.setText(String.valueOf(totalCarRecords));
            lblActiveRentalsTotal.setText(String.valueOf(bookedCars));
        } catch (FileNotFoundException e) {
            System.out.println("File not found: " + e.getMessage());
        }

        /* Bookings data */
        try {
            String bookingsFilePath = "src\\storage\\bookings.csv";
            int totalBookingRecords = StorageFunctions.countRecords(bookingsFilePath);
            int totalCompletedBookingRecords = StorageFunctions.countCompletedBookings(bookingsFilePath);
            int totalCancelledBookingRecords = StorageFunctions.countCancelledBookings(bookingsFilePath);
            double revenue = StorageFunctions.calculateTotalRevenue(bookingsFilePath);

            // Create a DecimalFormat instance with the desired pattern
            DecimalFormat df = new DecimalFormat("#,##0.00");
            // Format the revenue
            String formattedRevenue = df.format(revenue);

            lblNumberOfBookingsTotal.setText(String.valueOf(totalBookingRecords));
            lblCompletedBookingsTotal.setText(String.valueOf(totalCompletedBookingRecords));
            lblCancelledBookingsTotal.setText(String.valueOf(totalCancelledBookingRecords));
            lblRevenueTotal.setText(String.valueOf("N$ " + formattedRevenue));
        } catch (FileNotFoundException e) {
            System.out.println("File not found: " + e.getMessage());
        }

        lblFirstNameDynamic.setText("First name: " + user.getFirstName());
        lblLastNameDynamic.setText("Last name: " + user.getLastName());
        lblEmailDynamic.setText("Email: " + user.getEmail());

        lblPhoneNumberDynamic.setText("Phone number: " + user.getPhoneNumber());
        if (user.getDriversLicense().equals(""))
            lblDriverLicenseDynamic.setText("Driver license: not found");
        else
            lblDriverLicenseDynamic.setText("Driver license: " + user.getDriversLicense());
        lblUserTypeDynamic.setText("User type: " + user.getUserType());
        /* Others */
        Functions.showTime(lblCurrentTime);
        Functions.showDate(lblCurrentDate);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblLeenda = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblCarListing = new javax.swing.JLabel();
        lblBookings = new javax.swing.JLabel();
        lblUserManagement = new javax.swing.JLabel();
        btnLogout = new javax.swing.JToggleButton();
        pnlSubHeader = new javax.swing.JPanel();
        lblDashboardHeader = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        pnlDashoboardItem = new javax.swing.JPanel();
        lblUserIcon = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsers = new javax.swing.JLabel();
        lblTotalUsers = new javax.swing.JLabel();
        pnlDashoboardItem1 = new javax.swing.JPanel();
        lblPendingApprovalsIcon = new javax.swing.JLabel();
        lblPendingApproval = new javax.swing.JLabel();
        lblPendingApprovalsTotal = new javax.swing.JLabel();
        pnlDashoboardItem2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblDashboardHeader5 = new javax.swing.JLabel();
        lblActiveRentalsTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlDashoboardItem4 = new javax.swing.JPanel();
        lblCars = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblDashboardHeader9 = new javax.swing.JLabel();
        lblNumberOfCarsTotal = new javax.swing.JLabel();
        pnlDashoboardItem5 = new javax.swing.JPanel();
        lblNumberOfBookingsIcon = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblNumberOfBookings = new javax.swing.JLabel();
        lblNumberOfBookingsTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblDashboardHeader15 = new javax.swing.JLabel();
        lblDashboardHeader16 = new javax.swing.JLabel();
        pnlDashoboardItem6 = new javax.swing.JPanel();
        lblCompletedBookingsIcon = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblCompletedBookings = new javax.swing.JLabel();
        lblCompletedBookingsTotal = new javax.swing.JLabel();
        pnlDashoboardItem7 = new javax.swing.JPanel();
        lblCancelledBookingsIcon = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblCancelledBookings = new javax.swing.JLabel();
        lblCancelledBookingsTotal = new javax.swing.JLabel();
        pnlDashoboardItem8 = new javax.swing.JPanel();
        lblRevenueIcon = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblRevenue = new javax.swing.JLabel();
        lblRevenueTotal = new javax.swing.JLabel();
        pnlDashoboardItem9 = new javax.swing.JPanel();
        lblFirstNameDynamic = new javax.swing.JLabel();
        lblEmailDynamic = new javax.swing.JLabel();
        lblPhoneNumberDynamic = new javax.swing.JLabel();
        lblDriverLicenseDynamic = new javax.swing.JLabel();
        lblUserTypeDynamic = new javax.swing.JLabel();
        lblLastNameDynamic = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        lblCurrentTime = new javax.swing.JLabel();
        lblCurrentDate = new javax.swing.JLabel();
        pnlDashoboardItem11 = new javax.swing.JPanel();
        btnEditPersonalInformation = new javax.swing.JToggleButton();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblDriverLicense = new javax.swing.JLabel();
        txtDriverLicense = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(237, 223, 205));

        pnlHeader.setBackground(new java.awt.Color(217, 186, 164));

        lblLeenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblLeenda.setText("Leenda");

        lblDashboard.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCarListing.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCarListing.setText("Car listing");
        lblCarListing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCarListing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarListingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCarListingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCarListingMouseExited(evt);
            }
        });

        lblBookings.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBookings.setText("Bookings");
        lblBookings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBookingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBookingsMouseExited(evt);
            }
        });

        lblUserManagement.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUserManagement.setText("User management");
        lblUserManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUserManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserManagementOnClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserManagementMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserManagementMouseExited(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(237, 223, 205));
        btnLogout.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutOnClick(evt);
            }
        });

        pnlSubHeader.setBackground(new java.awt.Color(237, 223, 205));
        pnlSubHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDashboardHeader.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblDashboardHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboardHeader.setText("Dashboard");

        javax.swing.GroupLayout pnlSubHeaderLayout = new javax.swing.GroupLayout(pnlSubHeader);
        pnlSubHeader.setLayout(pnlSubHeaderLayout);
        pnlSubHeaderLayout.setHorizontalGroup(
            pnlSubHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubHeaderLayout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(lblDashboardHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubHeaderLayout.setVerticalGroup(
            pnlSubHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDashboardHeader)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblLeenda)
                .addGap(163, 163, 163)
                .addComponent(lblDashboard)
                .addGap(55, 55, 55)
                .addComponent(lblCarListing)
                .addGap(60, 60, 60)
                .addComponent(lblBookings)
                .addGap(61, 61, 61)
                .addComponent(lblUserManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(15, 15, 15))
            .addComponent(pnlSubHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeenda, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblUserManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarListing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSubHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDashboard.setBackground(new java.awt.Color(237, 223, 205));
        pnlDashboard.setPreferredSize(new java.awt.Dimension(1023, 500));

        pnlDashoboardItem.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem.setPreferredSize(new java.awt.Dimension(240, 83));

        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(217, 186, 164));

        lblUsers.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(133, 62, 52));
        lblUsers.setText("Number of users");

        lblTotalUsers.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTotalUsers.setForeground(new java.awt.Color(133, 62, 52));
        lblTotalUsers.setText("10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTotalUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblUsers)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDashoboardItemLayout = new javax.swing.GroupLayout(pnlDashoboardItem);
        pnlDashoboardItem.setLayout(pnlDashoboardItemLayout);
        pnlDashoboardItemLayout.setHorizontalGroup(
            pnlDashoboardItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserIcon)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashoboardItemLayout.setVerticalGroup(
            pnlDashoboardItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItemLayout.createSequentialGroup()
                .addGroup(pnlDashoboardItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashoboardItemLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblUserIcon))
                    .addGroup(pnlDashoboardItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlDashoboardItem1.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem1.setPreferredSize(new java.awt.Dimension(240, 83));

        lblPendingApprovalsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pending-approval.png"))); // NOI18N

        lblPendingApproval.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPendingApproval.setForeground(new java.awt.Color(133, 62, 52));
        lblPendingApproval.setText("Pending approvals");

        lblPendingApprovalsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPendingApprovalsTotal.setForeground(new java.awt.Color(133, 62, 52));
        lblPendingApprovalsTotal.setText("2");

        javax.swing.GroupLayout pnlDashoboardItem1Layout = new javax.swing.GroupLayout(pnlDashoboardItem1);
        pnlDashoboardItem1.setLayout(pnlDashoboardItem1Layout);
        pnlDashoboardItem1Layout.setHorizontalGroup(
            pnlDashoboardItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPendingApprovalsIcon)
                .addGroup(pnlDashoboardItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashoboardItem1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblPendingApprovalsTotal))
                    .addGroup(pnlDashoboardItem1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblPendingApproval)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlDashoboardItem1Layout.setVerticalGroup(
            pnlDashoboardItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDashoboardItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDashoboardItem1Layout.createSequentialGroup()
                        .addComponent(lblPendingApproval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPendingApprovalsTotal))
                    .addComponent(lblPendingApprovalsIcon))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlDashoboardItem2.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem2.setPreferredSize(new java.awt.Dimension(240, 83));

        jPanel3.setBackground(new java.awt.Color(217, 186, 164));

        lblDashboardHeader5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDashboardHeader5.setForeground(new java.awt.Color(133, 62, 52));
        lblDashboardHeader5.setText("Active rentals");

        lblActiveRentalsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblActiveRentalsTotal.setForeground(new java.awt.Color(133, 62, 52));
        lblActiveRentalsTotal.setText("2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblDashboardHeader5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblActiveRentalsTotal)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblDashboardHeader5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblActiveRentalsTotal)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/active-cars-admin.png"))); // NOI18N

        javax.swing.GroupLayout pnlDashoboardItem2Layout = new javax.swing.GroupLayout(pnlDashoboardItem2);
        pnlDashoboardItem2.setLayout(pnlDashoboardItem2Layout);
        pnlDashoboardItem2Layout.setHorizontalGroup(
            pnlDashoboardItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashoboardItem2Layout.setVerticalGroup(
            pnlDashoboardItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlDashoboardItem2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDashoboardItem4.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem4.setPreferredSize(new java.awt.Dimension(240, 83));

        lblCars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cars.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(217, 186, 164));

        lblDashboardHeader9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDashboardHeader9.setForeground(new java.awt.Color(133, 62, 52));
        lblDashboardHeader9.setText("Number of cars");

        lblNumberOfCarsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblNumberOfCarsTotal.setForeground(new java.awt.Color(133, 62, 52));
        lblNumberOfCarsTotal.setText("4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDashboardHeader9)
                .addGap(15, 15, 15))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblNumberOfCarsTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblDashboardHeader9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumberOfCarsTotal)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDashoboardItem4Layout = new javax.swing.GroupLayout(pnlDashoboardItem4);
        pnlDashoboardItem4.setLayout(pnlDashoboardItem4Layout);
        pnlDashoboardItem4Layout.setHorizontalGroup(
            pnlDashoboardItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblCars)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlDashoboardItem4Layout.setVerticalGroup(
            pnlDashoboardItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashoboardItem4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCars)
                .addGap(14, 14, 14))
        );

        pnlDashoboardItem5.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem5.setPreferredSize(new java.awt.Dimension(240, 83));

        lblNumberOfBookingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book.png"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(217, 186, 164));

        lblNumberOfBookings.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNumberOfBookings.setForeground(new java.awt.Color(133, 62, 52));
        lblNumberOfBookings.setText("Number of bookings");

        lblNumberOfBookingsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblNumberOfBookingsTotal.setForeground(new java.awt.Color(133, 62, 52));
        lblNumberOfBookingsTotal.setText("4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblNumberOfBookings)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblNumberOfBookingsTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumberOfBookings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumberOfBookingsTotal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(217, 186, 164));

        lblDashboardHeader15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDashboardHeader15.setForeground(new java.awt.Color(133, 62, 52));
        lblDashboardHeader15.setText("Bookings");

        lblDashboardHeader16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblDashboardHeader16.setForeground(new java.awt.Color(133, 62, 52));
        lblDashboardHeader16.setText("2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblDashboardHeader15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDashboardHeader16)
                .addGap(34, 34, 34))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDashboardHeader15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashboardHeader16)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDashoboardItem5Layout = new javax.swing.GroupLayout(pnlDashoboardItem5);
        pnlDashoboardItem5.setLayout(pnlDashoboardItem5Layout);
        pnlDashoboardItem5Layout.setHorizontalGroup(
            pnlDashoboardItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem5Layout.createSequentialGroup()
                .addGroup(pnlDashoboardItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashoboardItem5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNumberOfBookingsIcon)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDashoboardItem5Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashoboardItem5Layout.setVerticalGroup(
            pnlDashoboardItem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNumberOfBookingsIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDashoboardItem5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDashoboardItem6.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem6.setPreferredSize(new java.awt.Dimension(240, 83));

        lblCompletedBookingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/completed-bookings.png"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(217, 186, 164));

        lblCompletedBookings.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCompletedBookings.setForeground(new java.awt.Color(133, 62, 52));
        lblCompletedBookings.setText("Completed bookings");

        lblCompletedBookingsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCompletedBookingsTotal.setForeground(new java.awt.Color(133, 62, 52));
        lblCompletedBookingsTotal.setText("2");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lblCompletedBookingsTotal))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompletedBookings))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompletedBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompletedBookingsTotal)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDashoboardItem6Layout = new javax.swing.GroupLayout(pnlDashoboardItem6);
        pnlDashoboardItem6.setLayout(pnlDashoboardItem6Layout);
        pnlDashoboardItem6Layout.setHorizontalGroup(
            pnlDashoboardItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCompletedBookingsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        pnlDashoboardItem6Layout.setVerticalGroup(
            pnlDashoboardItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem6Layout.createSequentialGroup()
                .addGroup(pnlDashoboardItem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDashoboardItem6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDashoboardItem6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblCompletedBookingsIcon)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlDashoboardItem7.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem7.setPreferredSize(new java.awt.Dimension(240, 83));

        lblCancelledBookingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelled-bookings.png"))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(217, 186, 164));

        lblCancelledBookings.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCancelledBookings.setForeground(new java.awt.Color(133, 62, 52));
        lblCancelledBookings.setText("Cancelled bookings");

        lblCancelledBookingsTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCancelledBookingsTotal.setForeground(new java.awt.Color(133, 62, 52));
        lblCancelledBookingsTotal.setText("2");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancelledBookings))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblCancelledBookingsTotal))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancelledBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCancelledBookingsTotal)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDashoboardItem7Layout = new javax.swing.GroupLayout(pnlDashoboardItem7);
        pnlDashoboardItem7.setLayout(pnlDashoboardItem7Layout);
        pnlDashoboardItem7Layout.setHorizontalGroup(
            pnlDashoboardItem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancelledBookingsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashoboardItem7Layout.setVerticalGroup(
            pnlDashoboardItem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem7Layout.createSequentialGroup()
                .addGroup(pnlDashoboardItem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashoboardItem7Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblCancelledBookingsIcon))
                    .addGroup(pnlDashoboardItem7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlDashoboardItem8.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem8.setPreferredSize(new java.awt.Dimension(240, 83));

        lblRevenueIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N

        jPanel10.setBackground(new java.awt.Color(217, 186, 164));

        lblRevenue.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblRevenue.setForeground(new java.awt.Color(133, 62, 52));
        lblRevenue.setText("Revenue");

        lblRevenueTotal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRevenueTotal.setForeground(new java.awt.Color(133, 62, 52));
        lblRevenueTotal.setText("2");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRevenue)
                    .addComponent(lblRevenueTotal))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevenueTotal)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlDashoboardItem8Layout = new javax.swing.GroupLayout(pnlDashoboardItem8);
        pnlDashoboardItem8.setLayout(pnlDashoboardItem8Layout);
        pnlDashoboardItem8Layout.setHorizontalGroup(
            pnlDashoboardItem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRevenueIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        pnlDashoboardItem8Layout.setVerticalGroup(
            pnlDashoboardItem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem8Layout.createSequentialGroup()
                .addGroup(pnlDashoboardItem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDashoboardItem8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDashoboardItem8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblRevenueIcon)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlDashoboardItem9.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem9.setPreferredSize(new java.awt.Dimension(240, 83));

        lblFirstNameDynamic.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFirstNameDynamic.setText("First name: Kondwani");

        lblEmailDynamic.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEmailDynamic.setText("Email: kk30@gmail.com");

        lblPhoneNumberDynamic.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPhoneNumberDynamic.setText("Phone number: +264813257382");

        lblDriverLicenseDynamic.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDriverLicenseDynamic.setText("Driver license: 03458727458MA8");

        lblUserTypeDynamic.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblUserTypeDynamic.setText("User type: admin");

        lblLastNameDynamic.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLastNameDynamic.setText("Last name: Kunkwenzu");

        javax.swing.GroupLayout pnlDashoboardItem9Layout = new javax.swing.GroupLayout(pnlDashoboardItem9);
        pnlDashoboardItem9.setLayout(pnlDashoboardItem9Layout);
        pnlDashoboardItem9Layout.setHorizontalGroup(
            pnlDashoboardItem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem9Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlDashoboardItem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDriverLicenseDynamic)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashoboardItem9Layout.createSequentialGroup()
                        .addComponent(lblEmailDynamic)
                        .addGap(55, 55, 55))
                    .addComponent(lblFirstNameDynamic))
                .addGroup(pnlDashoboardItem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastNameDynamic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserTypeDynamic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhoneNumberDynamic, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );
        pnlDashoboardItem9Layout.setVerticalGroup(
            pnlDashoboardItem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDashoboardItem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstNameDynamic)
                    .addComponent(lblLastNameDynamic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDashoboardItem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumberDynamic)
                    .addComponent(lblEmailDynamic))
                .addGap(56, 56, 56)
                .addGroup(pnlDashoboardItem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserTypeDynamic)
                    .addComponent(lblDriverLicenseDynamic))
                .addGap(22, 22, 22))
        );

        pnlFooter.setBackground(new java.awt.Color(217, 186, 164));
        pnlFooter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlFooter.setPreferredSize(new java.awt.Dimension(240, 83));

        lblCurrentTime.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCurrentTime.setText("11:42:00 PM");

        lblCurrentDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCurrentDate.setText("Sunday, 22th September 2024");

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblCurrentTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 646, Short.MAX_VALUE)
                .addComponent(lblCurrentDate)
                .addGap(21, 21, 21))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentTime, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblCurrentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlDashoboardItem11.setBackground(new java.awt.Color(217, 186, 164));
        pnlDashoboardItem11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlDashoboardItem11.setPreferredSize(new java.awt.Dimension(240, 83));

        btnEditPersonalInformation.setBackground(new java.awt.Color(133, 62, 52));
        btnEditPersonalInformation.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnEditPersonalInformation.setForeground(new java.awt.Color(237, 223, 205));
        btnEditPersonalInformation.setText("Edit personal information");
        btnEditPersonalInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditPersonalInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPersonalInformationOnClick(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFirstName.setText("First name");

        txtFirstName.setBackground(new java.awt.Color(237, 223, 205));
        txtFirstName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setBackground(new java.awt.Color(237, 223, 205));
        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblPhoneNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblPhoneNumber.setText("Phone number");

        txtPhoneNumber.setBackground(new java.awt.Color(237, 223, 205));
        txtPhoneNumber.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblDriverLicense.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDriverLicense.setText("Driver license");

        txtDriverLicense.setBackground(new java.awt.Color(237, 223, 205));
        txtDriverLicense.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        lblLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblLastName.setText("Last name");

        txtLastName.setBackground(new java.awt.Color(237, 223, 205));
        txtLastName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        javax.swing.GroupLayout pnlDashoboardItem11Layout = new javax.swing.GroupLayout(pnlDashoboardItem11);
        pnlDashoboardItem11.setLayout(pnlDashoboardItem11Layout);
        pnlDashoboardItem11Layout.setHorizontalGroup(
            pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFirstName))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName)))
                            .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPhoneNumber))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashoboardItem11Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDriverLicense)
                            .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditPersonalInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlDashoboardItem11Layout.setVerticalGroup(
            pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                        .addComponent(lblFirstName)
                        .addGap(28, 28, 28))
                    .addGroup(pnlDashoboardItem11Layout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashoboardItem11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDriverLicense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditPersonalInformation)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDashboardLayout.createSequentialGroup()
                            .addComponent(pnlDashoboardItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlDashoboardItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(pnlDashoboardItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlDashoboardItem2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDashboardLayout.createSequentialGroup()
                            .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlDashboardLayout.createSequentialGroup()
                                    .addComponent(pnlDashoboardItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlDashoboardItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pnlDashoboardItem9, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlDashboardLayout.createSequentialGroup()
                                    .addComponent(pnlDashoboardItem7, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlDashoboardItem8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pnlDashoboardItem11, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDashoboardItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDashoboardItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDashoboardItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDashoboardItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDashoboardItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDashoboardItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDashoboardItem7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDashoboardItem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDashoboardItem11, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(pnlDashoboardItem9, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(pnlFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCarListingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarListingMouseClicked
        this.dispose();
        new CarListing(user);
    }//GEN-LAST:event_lblCarListingMouseClicked

    private void lblBookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookingsMouseClicked
        this.dispose();
        new BookingPage(user);
    }//GEN-LAST:event_lblBookingsMouseClicked

    private void btnEditPersonalInformationOnClick(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditPersonalInformationOnClick
        // Regular expressions
        String nameRegex = "^(?!.*\\s)(!?[A-Z][a-zA-Z]*)$"; // First letter uppercase, then letters or '!'
        String emailRegex = "^[\\w-\\.]+@[\\w-]+\\.[a-z]{2,4}$"; // Basic email validation
        String phoneRegex = "^\\+\\d{1,4}\\d+$"; // Phone number starts with + followed by digits

        // Variables declaration and assignment (trim input to remove leading/trailing
        // spaces)
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim(); // Use getText(), not getName() for JTextField
        String email = txtEmail.getText().trim();
        String phoneNumber = txtPhoneNumber.getText().trim();
        String driverLicense = txtDriverLicense.getText().trim();

        // Check if at least one field is filled
        if (firstName.equals("") && lastName.equals("") && email.equals("") && phoneNumber.equals("")
                && driverLicense.equals("")) {
            JOptionPane.showMessageDialog(null, "At least one field must be filled to update!", "Update Failed",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // Check if at least one field is filled
            if (firstName.equals("") && lastName.equals("") && email.equals("") && phoneNumber.equals("")) {
                JOptionPane.showMessageDialog(null, "At least one field must be filled to update!", "Update Failed",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                // Validation for each non-empty field
                if (!firstName.equals("") && !firstName.matches(nameRegex)) {
                    JOptionPane.showMessageDialog(this,
                            "First name is invalid. \nOnly letters and '!' are allowed, and it must start with an uppercase letter or '!' followed by an uppercase letter.",
                            "Invalid First Name", JOptionPane.ERROR_MESSAGE);
                    return; // Stop if validation fails
                }
                if (!lastName.equals("") && !lastName.matches(nameRegex)) {
                    JOptionPane.showMessageDialog(this,
                            "Last name is invalid. \nOnly letters and '!' are allowed, and it must start with an uppercase letter or '!' followed by an uppercase letter.",
                            "Invalid Last Name", JOptionPane.ERROR_MESSAGE);
                    return; // Stop if validation fails
                }
                if (!email.equals("") && !email.matches(emailRegex)) {
                    JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Invalid Email",
                            JOptionPane.ERROR_MESSAGE);
                    return; // Stop if validation fails
                }
                if (!phoneNumber.equals("") && !phoneNumber.matches(phoneRegex)) {
                    JOptionPane.showMessageDialog(this,
                            "Phone number must start with +country code \nand contain only numbers.",
                            "Invalid Phone Number", JOptionPane.ERROR_MESSAGE);
                    return; // Stop if validation fails
                }

                if (AuthFunctions.doesEmailExist(email)) {
                    JOptionPane.showMessageDialog(this, "Email is already in use. Please choose another one.",
                            "Email Exists", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Check and update each field only if it's not empty
                    if (!firstName.equals("")) {
                        user.setFirstName(firstName);
                    }
                    if (!lastName.equals("")) {
                        user.setLastName(lastName);
                    }
                    if (!email.equals("")) {
                        user.setEmail(email);
                    }
                    if (!phoneNumber.equals("")) {
                        user.setPhoneNumber(phoneNumber);
                    }
                    if (!driverLicense.equals("")) {
                        user.setDriversLicense(driverLicense);
                    }

                    // Now update the user in the CSV file
                    try {
                        StorageFunctions.updateUserRecord(user);
                        JOptionPane.showMessageDialog(null, "User updated successfully!");
                        // Update information in the screen
                        lblFirstNameDynamic.setText("First name: " + user.getFirstName());
                        lblLastNameDynamic.setText("Last name: " + user.getLastName());
                        lblEmailDynamic.setText("Email: " + user.getEmail());
                        lblPhoneNumberDynamic.setText("Phone number: " + user.getPhoneNumber());
                        if (user.getDriversLicense().equals(""))
                            lblDriverLicenseDynamic.setText("Driver license: not found");
                        else
                            lblDriverLicenseDynamic.setText("Driver license: " + user.getDriversLicense());
                    } catch (IOException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Error updating user data.");
                    }
                }
            }
        }
    }// GEN-LAST:event_btnEditPersonalInformationOnClick


    
    private void lblCarListingMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblCarListingMouseEntered
        Functions.changeColorOfTheLabelOfTheHeaderWhenEntering(lblCarListing);
    }// GEN-LAST:event_lblCarListingMouseEntered

    private void lblCarListingMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblCarListingMouseExited
        Functions.changeColorOfTheLabelOfTheHeaderWhenExiting(lblCarListing);
    }// GEN-LAST:event_lblCarListingMouseExited

    private void lblBookingsMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblBookingsMouseEntered
        Functions.changeColorOfTheLabelOfTheHeaderWhenEntering(lblBookings);
    }// GEN-LAST:event_lblBookingsMouseEntered

    private void lblBookingsMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblBookingsMouseExited
        Functions.changeColorOfTheLabelOfTheHeaderWhenExiting(lblBookings);
    }// GEN-LAST:event_lblBookingsMouseExited

    private void lblUserManagementMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblUserManagementMouseEntered
        Functions.changeColorOfTheLabelOfTheHeaderWhenEntering(lblUserManagement);
    }// GEN-LAST:event_lblUserManagementMouseEntered

    private void lblUserManagementMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblUserManagementMouseExited
        Functions.changeColorOfTheLabelOfTheHeaderWhenExiting(lblUserManagement);
    }// GEN-LAST:event_lblUserManagementMouseExited

    private void lblUserManagementOnClick(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lblUserManagementOnClick
        this.dispose();
        new UserManagementPage(user);
    }// GEN-LAST:event_lblUserManagementOnClick

    private void btnLogoutOnClick(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnLogoutOnClick
        this.dispose();
        new LoginPage();
    }// GEN-LAST:event_btnLogoutOnClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEditPersonalInformation;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblActiveRentalsTotal;
    private javax.swing.JLabel lblBookings;
    private javax.swing.JLabel lblCancelledBookings;
    private javax.swing.JLabel lblCancelledBookingsIcon;
    private javax.swing.JLabel lblCancelledBookingsTotal;
    private javax.swing.JLabel lblCarListing;
    private javax.swing.JLabel lblCars;
    private javax.swing.JLabel lblCompletedBookings;
    private javax.swing.JLabel lblCompletedBookingsIcon;
    private javax.swing.JLabel lblCompletedBookingsTotal;
    private javax.swing.JLabel lblCurrentDate;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboardHeader;
    private javax.swing.JLabel lblDashboardHeader15;
    private javax.swing.JLabel lblDashboardHeader16;
    private javax.swing.JLabel lblDashboardHeader5;
    private javax.swing.JLabel lblDashboardHeader9;
    private javax.swing.JLabel lblDriverLicense;
    private javax.swing.JLabel lblDriverLicenseDynamic;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailDynamic;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstNameDynamic;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastNameDynamic;
    private javax.swing.JLabel lblLeenda;
    private javax.swing.JLabel lblNumberOfBookings;
    private javax.swing.JLabel lblNumberOfBookingsIcon;
    private javax.swing.JLabel lblNumberOfBookingsTotal;
    private javax.swing.JLabel lblNumberOfCarsTotal;
    private javax.swing.JLabel lblPendingApproval;
    private javax.swing.JLabel lblPendingApprovalsIcon;
    private javax.swing.JLabel lblPendingApprovalsTotal;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumberDynamic;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JLabel lblRevenueIcon;
    private javax.swing.JLabel lblRevenueTotal;
    private javax.swing.JLabel lblTotalUsers;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblUserManagement;
    private javax.swing.JLabel lblUserTypeDynamic;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDashoboardItem;
    private javax.swing.JPanel pnlDashoboardItem1;
    private javax.swing.JPanel pnlDashoboardItem11;
    private javax.swing.JPanel pnlDashoboardItem2;
    private javax.swing.JPanel pnlDashoboardItem4;
    private javax.swing.JPanel pnlDashoboardItem5;
    private javax.swing.JPanel pnlDashoboardItem6;
    private javax.swing.JPanel pnlDashoboardItem7;
    private javax.swing.JPanel pnlDashoboardItem8;
    private javax.swing.JPanel pnlDashoboardItem9;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSubHeader;
    private javax.swing.JTextField txtDriverLicense;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}

/**
 *
 * @author: <edande - 223134902/>
 */
