/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package leendauserdashboard;
import models.User;

/**
 *
 * @author Jaden
 */
public class CarBooking extends javax.swing.JFrame {
    public User user;
    /**
     * Creates new form UserDashboard
     */
    public CarBooking(User user) {
        this.user = user;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        NavPanel = new javax.swing.JPanel();
        Leenda = new javax.swing.JLabel();
        Booking = new javax.swing.JButton();
        Dashboard = new javax.swing.JButton();
        BookingsPanel = new javax.swing.JPanel();
        Bookings14B = new javax.swing.JLabel();
        ListingScollingPanel = new javax.swing.JScrollPane();
        carListing = new javax.swing.JPanel();
        carListing1 = new javax.swing.JPanel();
        carImageBox = new javax.swing.JPanel();
        CarImage = new javax.swing.JLabel();
        CarModel = new javax.swing.JLabel();
        CarYear = new javax.swing.JLabel();
        CarBrand = new javax.swing.JLabel();
        CarRating = new javax.swing.JLabel();
        CarOwner = new javax.swing.JLabel();
        CarOwnerRating = new javax.swing.JLabel();
        TextCarBooked = new javax.swing.JLabel();
        NumberOfBookings = new javax.swing.JLabel();
        TextCarRatings = new javax.swing.JLabel();
        TextCarComments = new javax.swing.JLabel();
        NumberOfComments = new javax.swing.JLabel();
        TextCarDateListed = new javax.swing.JLabel();
        DateCarListed = new javax.swing.JLabel();
        TextOwnerRating = new javax.swing.JLabel();
        carListing2 = new javax.swing.JPanel();
        carImageBox1 = new javax.swing.JPanel();
        CarImage1 = new javax.swing.JLabel();
        CarModel1 = new javax.swing.JLabel();
        CarYear1 = new javax.swing.JLabel();
        CarBrand1 = new javax.swing.JLabel();
        CarRating1 = new javax.swing.JLabel();
        CarOwner1 = new javax.swing.JLabel();
        CarOwnerRating1 = new javax.swing.JLabel();
        TextCarBooked1 = new javax.swing.JLabel();
        NumberOfBookings1 = new javax.swing.JLabel();
        TextCarRatings1 = new javax.swing.JLabel();
        TextCarComments1 = new javax.swing.JLabel();
        NumberOfComments1 = new javax.swing.JLabel();
        TextCarDateListed1 = new javax.swing.JLabel();
        DateCarListed1 = new javax.swing.JLabel();
        TextOwnerRating1 = new javax.swing.JLabel();
        carListing3 = new javax.swing.JPanel();
        carImageBox2 = new javax.swing.JPanel();
        CarImage2 = new javax.swing.JLabel();
        CarModel2 = new javax.swing.JLabel();
        CarYear2 = new javax.swing.JLabel();
        CarBrand2 = new javax.swing.JLabel();
        CarRating2 = new javax.swing.JLabel();
        CarOwner2 = new javax.swing.JLabel();
        CarOwnerRating2 = new javax.swing.JLabel();
        TextCarBooked2 = new javax.swing.JLabel();
        NumberOfBookings2 = new javax.swing.JLabel();
        TextCarRatings2 = new javax.swing.JLabel();
        TextCarComments2 = new javax.swing.JLabel();
        NumberOfComments2 = new javax.swing.JLabel();
        TextCarDateListed2 = new javax.swing.JLabel();
        DateCarListed2 = new javax.swing.JLabel();
        TextOwnerRating2 = new javax.swing.JLabel();
        carListing4 = new javax.swing.JPanel();
        carImageBox3 = new javax.swing.JPanel();
        CarImage3 = new javax.swing.JLabel();
        CarModel3 = new javax.swing.JLabel();
        CarYear3 = new javax.swing.JLabel();
        CarBrand3 = new javax.swing.JLabel();
        CarRating3 = new javax.swing.JLabel();
        CarOwner3 = new javax.swing.JLabel();
        CarOwnerRating3 = new javax.swing.JLabel();
        TextCarBooked3 = new javax.swing.JLabel();
        NumberOfBookings3 = new javax.swing.JLabel();
        TextCarRatings3 = new javax.swing.JLabel();
        TextCarComments3 = new javax.swing.JLabel();
        NumberOfComments3 = new javax.swing.JLabel();
        TextCarDateListed3 = new javax.swing.JLabel();
        DateCarListed3 = new javax.swing.JLabel();
        TextOwnerRating3 = new javax.swing.JLabel();
        carListing5 = new javax.swing.JPanel();
        carImageBox4 = new javax.swing.JPanel();
        CarImage4 = new javax.swing.JLabel();
        CarModel4 = new javax.swing.JLabel();
        CarYear4 = new javax.swing.JLabel();
        CarBrand4 = new javax.swing.JLabel();
        CarRating4 = new javax.swing.JLabel();
        CarOwner4 = new javax.swing.JLabel();
        CarOwnerRating4 = new javax.swing.JLabel();
        TextCarBooked4 = new javax.swing.JLabel();
        NumberOfBookings4 = new javax.swing.JLabel();
        TextCarRatings4 = new javax.swing.JLabel();
        TextCarComments4 = new javax.swing.JLabel();
        NumberOfComments4 = new javax.swing.JLabel();
        TextCarDateListed4 = new javax.swing.JLabel();
        DateCarListed4 = new javax.swing.JLabel();
        TextOwnerRating4 = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        EditProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(237, 223, 205));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        Background.setBackground(new java.awt.Color(237, 223, 205));

        NavPanel.setBackground(new java.awt.Color(217, 186, 164));
        NavPanel.setForeground(new java.awt.Color(217, 186, 164));

        Leenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Leenda.setForeground(new java.awt.Color(133, 62, 52));
        Leenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Leenda.setText("Leenda");

        Booking.setBackground(new java.awt.Color(237, 223, 205));
        Booking.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Booking.setForeground(new java.awt.Color(133, 62, 52));
        Booking.setText("Bookings");
        Booking.setToolTipText("Check out the catalog, something might catch your eye.");
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });
        Booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingActionPerformed(evt);
            }
        });

        Dashboard.setBackground(new java.awt.Color(237, 223, 205));
        Dashboard.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(133, 62, 52));
        Dashboard.setText("Dashboard");
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavPanelLayout = new javax.swing.GroupLayout(NavPanel);
        NavPanel.setLayout(NavPanelLayout);
        NavPanelLayout.setHorizontalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Leenda, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavPanelLayout.setVerticalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addGroup(NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Leenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BookingsPanel.setBackground(new java.awt.Color(237, 223, 205));
        BookingsPanel.setForeground(new java.awt.Color(237, 223, 205));

        Bookings14B.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Bookings14B.setForeground(new java.awt.Color(133, 62, 52));
        Bookings14B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bookings14B.setText("Bookings");

        javax.swing.GroupLayout BookingsPanelLayout = new javax.swing.GroupLayout(BookingsPanel);
        BookingsPanel.setLayout(BookingsPanelLayout);
        BookingsPanelLayout.setHorizontalGroup(
            BookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bookings14B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BookingsPanelLayout.setVerticalGroup(
            BookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bookings14B)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        carListing.setBackground(new java.awt.Color(217, 186, 164));

        carListing1.setBackground(new java.awt.Color(217, 186, 164));
        carListing1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CarImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarImage.setText("CarImage");

        javax.swing.GroupLayout carImageBoxLayout = new javax.swing.GroupLayout(carImageBox);
        carImageBox.setLayout(carImageBoxLayout);
        carImageBoxLayout.setHorizontalGroup(
            carImageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        carImageBoxLayout.setVerticalGroup(
            carImageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CarModel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarModel.setForeground(new java.awt.Color(133, 62, 52));
        CarModel.setText("Car Model");

        CarYear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarYear.setForeground(new java.awt.Color(133, 62, 52));
        CarYear.setText("Car Year");

        CarBrand.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarBrand.setForeground(new java.awt.Color(133, 62, 52));
        CarBrand.setText("Car Brand");

        CarRating.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarRating.setForeground(new java.awt.Color(133, 62, 52));
        CarRating.setText("0/5");

        CarOwner.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwner.setForeground(new java.awt.Color(133, 62, 52));
        CarOwner.setText("Car Owner");

        CarOwnerRating.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwnerRating.setForeground(new java.awt.Color(133, 62, 52));
        CarOwnerRating.setText("Owner Rating");

        TextCarBooked.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarBooked.setForeground(new java.awt.Color(133, 62, 52));
        TextCarBooked.setText("Booked:");

        NumberOfBookings.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfBookings.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfBookings.setText("0");

        TextCarRatings.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarRatings.setForeground(new java.awt.Color(133, 62, 52));
        TextCarRatings.setText("Ratings:");

        TextCarComments.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarComments.setForeground(new java.awt.Color(133, 62, 52));
        TextCarComments.setText("Comments:");

        NumberOfComments.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfComments.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfComments.setText("000");

        TextCarDateListed.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarDateListed.setForeground(new java.awt.Color(133, 62, 52));
        TextCarDateListed.setText("Date Listed:");

        DateCarListed.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        DateCarListed.setForeground(new java.awt.Color(133, 62, 52));
        DateCarListed.setText("DD-MM-YYYY");

        TextOwnerRating.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextOwnerRating.setForeground(new java.awt.Color(133, 62, 52));
        TextOwnerRating.setText("Rating:");

        javax.swing.GroupLayout carListing1Layout = new javax.swing.GroupLayout(carListing1);
        carListing1.setLayout(carListing1Layout);
        carListing1Layout.setHorizontalGroup(
            carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing1Layout.createSequentialGroup()
                .addComponent(carImageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListing1Layout.createSequentialGroup()
                        .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing1Layout.createSequentialGroup()
                                .addComponent(CarOwner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextOwnerRating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarOwnerRating))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing1Layout.createSequentialGroup()
                                .addComponent(CarBrand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarModel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarYear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextCarComments)
                            .addGroup(carListing1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(TextCarRatings)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarRating)
                            .addComponent(NumberOfComments)))
                    .addGroup(carListing1Layout.createSequentialGroup()
                        .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carListing1Layout.createSequentialGroup()
                                .addComponent(TextCarBooked)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOfBookings))
                            .addGroup(carListing1Layout.createSequentialGroup()
                                .addComponent(TextCarDateListed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateCarListed)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        carListing1Layout.setVerticalGroup(
            carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarModel)
                    .addComponent(CarYear)
                    .addComponent(CarBrand)
                    .addComponent(CarRating)
                    .addComponent(TextCarRatings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarOwner)
                    .addComponent(CarOwnerRating)
                    .addComponent(TextCarComments)
                    .addComponent(NumberOfComments)
                    .addComponent(TextOwnerRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarBooked)
                    .addComponent(NumberOfBookings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarDateListed)
                    .addComponent(DateCarListed))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(carImageBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        carListing2.setBackground(new java.awt.Color(217, 186, 164));
        carListing2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CarImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarImage1.setText("CarImage");

        javax.swing.GroupLayout carImageBox1Layout = new javax.swing.GroupLayout(carImageBox1);
        carImageBox1.setLayout(carImageBox1Layout);
        carImageBox1Layout.setHorizontalGroup(
            carImageBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        carImageBox1Layout.setVerticalGroup(
            carImageBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CarModel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarModel1.setForeground(new java.awt.Color(133, 62, 52));
        CarModel1.setText("Car Model");

        CarYear1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarYear1.setForeground(new java.awt.Color(133, 62, 52));
        CarYear1.setText("Car Year");

        CarBrand1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarBrand1.setForeground(new java.awt.Color(133, 62, 52));
        CarBrand1.setText("Car Brand");

        CarRating1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarRating1.setForeground(new java.awt.Color(133, 62, 52));
        CarRating1.setText("0/5");

        CarOwner1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwner1.setForeground(new java.awt.Color(133, 62, 52));
        CarOwner1.setText("Car Owner");

        CarOwnerRating1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwnerRating1.setForeground(new java.awt.Color(133, 62, 52));
        CarOwnerRating1.setText("Owner Rating");

        TextCarBooked1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarBooked1.setForeground(new java.awt.Color(133, 62, 52));
        TextCarBooked1.setText("Booked:");

        NumberOfBookings1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfBookings1.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfBookings1.setText("0");

        TextCarRatings1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarRatings1.setForeground(new java.awt.Color(133, 62, 52));
        TextCarRatings1.setText("Ratings:");

        TextCarComments1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarComments1.setForeground(new java.awt.Color(133, 62, 52));
        TextCarComments1.setText("Comments:");

        NumberOfComments1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfComments1.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfComments1.setText("000");

        TextCarDateListed1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarDateListed1.setForeground(new java.awt.Color(133, 62, 52));
        TextCarDateListed1.setText("Date Listed:");

        DateCarListed1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        DateCarListed1.setForeground(new java.awt.Color(133, 62, 52));
        DateCarListed1.setText("DD-MM-YYYY");

        TextOwnerRating1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextOwnerRating1.setForeground(new java.awt.Color(133, 62, 52));
        TextOwnerRating1.setText("Rating:");

        javax.swing.GroupLayout carListing2Layout = new javax.swing.GroupLayout(carListing2);
        carListing2.setLayout(carListing2Layout);
        carListing2Layout.setHorizontalGroup(
            carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing2Layout.createSequentialGroup()
                .addComponent(carImageBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListing2Layout.createSequentialGroup()
                        .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing2Layout.createSequentialGroup()
                                .addComponent(CarOwner1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextOwnerRating1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarOwnerRating1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing2Layout.createSequentialGroup()
                                .addComponent(CarBrand1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarModel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarYear1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextCarComments1)
                            .addComponent(TextCarRatings1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarRating1)
                            .addComponent(NumberOfComments1)))
                    .addGroup(carListing2Layout.createSequentialGroup()
                        .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carListing2Layout.createSequentialGroup()
                                .addComponent(TextCarBooked1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOfBookings1))
                            .addGroup(carListing2Layout.createSequentialGroup()
                                .addComponent(TextCarDateListed1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateCarListed1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        carListing2Layout.setVerticalGroup(
            carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarModel1)
                    .addComponent(CarYear1)
                    .addComponent(CarBrand1)
                    .addComponent(CarRating1)
                    .addComponent(TextCarRatings1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarOwner1)
                    .addComponent(CarOwnerRating1)
                    .addComponent(TextCarComments1)
                    .addComponent(NumberOfComments1)
                    .addComponent(TextOwnerRating1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarBooked1)
                    .addComponent(NumberOfBookings1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarDateListed1)
                    .addComponent(DateCarListed1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(carImageBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        carListing3.setBackground(new java.awt.Color(217, 186, 164));
        carListing3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CarImage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarImage2.setText("CarImage");

        javax.swing.GroupLayout carImageBox2Layout = new javax.swing.GroupLayout(carImageBox2);
        carImageBox2.setLayout(carImageBox2Layout);
        carImageBox2Layout.setHorizontalGroup(
            carImageBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        carImageBox2Layout.setVerticalGroup(
            carImageBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CarModel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarModel2.setForeground(new java.awt.Color(133, 62, 52));
        CarModel2.setText("Car Model");

        CarYear2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarYear2.setForeground(new java.awt.Color(133, 62, 52));
        CarYear2.setText("Car Year");

        CarBrand2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarBrand2.setForeground(new java.awt.Color(133, 62, 52));
        CarBrand2.setText("Car Brand");

        CarRating2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarRating2.setForeground(new java.awt.Color(133, 62, 52));
        CarRating2.setText("0/5");

        CarOwner2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwner2.setForeground(new java.awt.Color(133, 62, 52));
        CarOwner2.setText("Car Owner");

        CarOwnerRating2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwnerRating2.setForeground(new java.awt.Color(133, 62, 52));
        CarOwnerRating2.setText("Owner Rating");

        TextCarBooked2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarBooked2.setForeground(new java.awt.Color(133, 62, 52));
        TextCarBooked2.setText("Booked:");

        NumberOfBookings2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfBookings2.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfBookings2.setText("0");

        TextCarRatings2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarRatings2.setForeground(new java.awt.Color(133, 62, 52));
        TextCarRatings2.setText("Ratings:");

        TextCarComments2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarComments2.setForeground(new java.awt.Color(133, 62, 52));
        TextCarComments2.setText("Comments:");

        NumberOfComments2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfComments2.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfComments2.setText("000");

        TextCarDateListed2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarDateListed2.setForeground(new java.awt.Color(133, 62, 52));
        TextCarDateListed2.setText("Date Listed:");

        DateCarListed2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        DateCarListed2.setForeground(new java.awt.Color(133, 62, 52));
        DateCarListed2.setText("DD-MM-YYYY");

        TextOwnerRating2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextOwnerRating2.setForeground(new java.awt.Color(133, 62, 52));
        TextOwnerRating2.setText("Rating:");

        javax.swing.GroupLayout carListing3Layout = new javax.swing.GroupLayout(carListing3);
        carListing3.setLayout(carListing3Layout);
        carListing3Layout.setHorizontalGroup(
            carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing3Layout.createSequentialGroup()
                .addComponent(carImageBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListing3Layout.createSequentialGroup()
                        .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing3Layout.createSequentialGroup()
                                .addComponent(CarOwner2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextOwnerRating2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarOwnerRating2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing3Layout.createSequentialGroup()
                                .addComponent(CarBrand2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarModel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarYear2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextCarComments2)
                            .addComponent(TextCarRatings2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarRating2)
                            .addComponent(NumberOfComments2)))
                    .addGroup(carListing3Layout.createSequentialGroup()
                        .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carListing3Layout.createSequentialGroup()
                                .addComponent(TextCarBooked2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOfBookings2))
                            .addGroup(carListing3Layout.createSequentialGroup()
                                .addComponent(TextCarDateListed2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateCarListed2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        carListing3Layout.setVerticalGroup(
            carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarModel2)
                    .addComponent(CarYear2)
                    .addComponent(CarBrand2)
                    .addComponent(CarRating2)
                    .addComponent(TextCarRatings2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarOwner2)
                    .addComponent(CarOwnerRating2)
                    .addComponent(TextCarComments2)
                    .addComponent(NumberOfComments2)
                    .addComponent(TextOwnerRating2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarBooked2)
                    .addComponent(NumberOfBookings2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarDateListed2)
                    .addComponent(DateCarListed2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(carImageBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        carListing4.setBackground(new java.awt.Color(217, 186, 164));
        carListing4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CarImage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarImage3.setText("CarImage");

        javax.swing.GroupLayout carImageBox3Layout = new javax.swing.GroupLayout(carImageBox3);
        carImageBox3.setLayout(carImageBox3Layout);
        carImageBox3Layout.setHorizontalGroup(
            carImageBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        carImageBox3Layout.setVerticalGroup(
            carImageBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CarModel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarModel3.setForeground(new java.awt.Color(133, 62, 52));
        CarModel3.setText("Car Model");

        CarYear3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarYear3.setForeground(new java.awt.Color(133, 62, 52));
        CarYear3.setText("Car Year");

        CarBrand3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarBrand3.setForeground(new java.awt.Color(133, 62, 52));
        CarBrand3.setText("Car Brand");

        CarRating3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarRating3.setForeground(new java.awt.Color(133, 62, 52));
        CarRating3.setText("0/5");

        CarOwner3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwner3.setForeground(new java.awt.Color(133, 62, 52));
        CarOwner3.setText("Car Owner");

        CarOwnerRating3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwnerRating3.setForeground(new java.awt.Color(133, 62, 52));
        CarOwnerRating3.setText("Owner Rating");

        TextCarBooked3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarBooked3.setForeground(new java.awt.Color(133, 62, 52));
        TextCarBooked3.setText("Booked:");

        NumberOfBookings3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfBookings3.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfBookings3.setText("0");

        TextCarRatings3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarRatings3.setForeground(new java.awt.Color(133, 62, 52));
        TextCarRatings3.setText("Ratings:");

        TextCarComments3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarComments3.setForeground(new java.awt.Color(133, 62, 52));
        TextCarComments3.setText("Comments:");

        NumberOfComments3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfComments3.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfComments3.setText("000");

        TextCarDateListed3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarDateListed3.setForeground(new java.awt.Color(133, 62, 52));
        TextCarDateListed3.setText("Date Listed:");

        DateCarListed3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        DateCarListed3.setForeground(new java.awt.Color(133, 62, 52));
        DateCarListed3.setText("DD-MM-YYYY");

        TextOwnerRating3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextOwnerRating3.setForeground(new java.awt.Color(133, 62, 52));
        TextOwnerRating3.setText("Rating:");

        javax.swing.GroupLayout carListing4Layout = new javax.swing.GroupLayout(carListing4);
        carListing4.setLayout(carListing4Layout);
        carListing4Layout.setHorizontalGroup(
            carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing4Layout.createSequentialGroup()
                .addComponent(carImageBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListing4Layout.createSequentialGroup()
                        .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing4Layout.createSequentialGroup()
                                .addComponent(CarOwner3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextOwnerRating3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarOwnerRating3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing4Layout.createSequentialGroup()
                                .addComponent(CarBrand3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarModel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarYear3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextCarComments3)
                            .addComponent(TextCarRatings3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarRating3)
                            .addComponent(NumberOfComments3)))
                    .addGroup(carListing4Layout.createSequentialGroup()
                        .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carListing4Layout.createSequentialGroup()
                                .addComponent(TextCarBooked3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOfBookings3))
                            .addGroup(carListing4Layout.createSequentialGroup()
                                .addComponent(TextCarDateListed3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateCarListed3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        carListing4Layout.setVerticalGroup(
            carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarModel3)
                    .addComponent(CarYear3)
                    .addComponent(CarBrand3)
                    .addComponent(CarRating3)
                    .addComponent(TextCarRatings3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarOwner3)
                    .addComponent(CarOwnerRating3)
                    .addComponent(TextCarComments3)
                    .addComponent(NumberOfComments3)
                    .addComponent(TextOwnerRating3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarBooked3)
                    .addComponent(NumberOfBookings3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarDateListed3)
                    .addComponent(DateCarListed3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(carImageBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        carListing5.setBackground(new java.awt.Color(217, 186, 164));
        carListing5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        CarImage4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarImage4.setText("CarImage");

        javax.swing.GroupLayout carImageBox4Layout = new javax.swing.GroupLayout(carImageBox4);
        carImageBox4.setLayout(carImageBox4Layout);
        carImageBox4Layout.setHorizontalGroup(
            carImageBox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );
        carImageBox4Layout.setVerticalGroup(
            carImageBox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CarImage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CarModel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarModel4.setForeground(new java.awt.Color(133, 62, 52));
        CarModel4.setText("Car Model");

        CarYear4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarYear4.setForeground(new java.awt.Color(133, 62, 52));
        CarYear4.setText("Car Year");

        CarBrand4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CarBrand4.setForeground(new java.awt.Color(133, 62, 52));
        CarBrand4.setText("Car Brand");

        CarRating4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarRating4.setForeground(new java.awt.Color(133, 62, 52));
        CarRating4.setText("0/5");

        CarOwner4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwner4.setForeground(new java.awt.Color(133, 62, 52));
        CarOwner4.setText("Car Owner");

        CarOwnerRating4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CarOwnerRating4.setForeground(new java.awt.Color(133, 62, 52));
        CarOwnerRating4.setText("Owner Rating");

        TextCarBooked4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarBooked4.setForeground(new java.awt.Color(133, 62, 52));
        TextCarBooked4.setText("Booked:");

        NumberOfBookings4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfBookings4.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfBookings4.setText("0");

        TextCarRatings4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarRatings4.setForeground(new java.awt.Color(133, 62, 52));
        TextCarRatings4.setText("Ratings:");

        TextCarComments4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarComments4.setForeground(new java.awt.Color(133, 62, 52));
        TextCarComments4.setText("Comments:");

        NumberOfComments4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        NumberOfComments4.setForeground(new java.awt.Color(133, 62, 52));
        NumberOfComments4.setText("000");

        TextCarDateListed4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextCarDateListed4.setForeground(new java.awt.Color(133, 62, 52));
        TextCarDateListed4.setText("Date Listed:");

        DateCarListed4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        DateCarListed4.setForeground(new java.awt.Color(133, 62, 52));
        DateCarListed4.setText("DD-MM-YYYY");

        TextOwnerRating4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TextOwnerRating4.setForeground(new java.awt.Color(133, 62, 52));
        TextOwnerRating4.setText("Rating:");

        javax.swing.GroupLayout carListing5Layout = new javax.swing.GroupLayout(carListing5);
        carListing5.setLayout(carListing5Layout);
        carListing5Layout.setHorizontalGroup(
            carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing5Layout.createSequentialGroup()
                .addComponent(carImageBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, carListing5Layout.createSequentialGroup()
                        .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing5Layout.createSequentialGroup()
                                .addComponent(CarOwner4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextOwnerRating4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarOwnerRating4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, carListing5Layout.createSequentialGroup()
                                .addComponent(CarBrand4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarModel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CarYear4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                        .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextCarComments4)
                            .addComponent(TextCarRatings4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarRating4)
                            .addComponent(NumberOfComments4)))
                    .addGroup(carListing5Layout.createSequentialGroup()
                        .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(carListing5Layout.createSequentialGroup()
                                .addComponent(TextCarBooked4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOfBookings4))
                            .addGroup(carListing5Layout.createSequentialGroup()
                                .addComponent(TextCarDateListed4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateCarListed4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        carListing5Layout.setVerticalGroup(
            carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListing5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarModel4)
                    .addComponent(CarYear4)
                    .addComponent(CarBrand4)
                    .addComponent(CarRating4)
                    .addComponent(TextCarRatings4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarOwner4)
                    .addComponent(CarOwnerRating4)
                    .addComponent(TextCarComments4)
                    .addComponent(NumberOfComments4)
                    .addComponent(TextOwnerRating4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarBooked4)
                    .addComponent(NumberOfBookings4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(carListing5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCarDateListed4)
                    .addComponent(DateCarListed4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(carImageBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout carListingLayout = new javax.swing.GroupLayout(carListing);
        carListing.setLayout(carListingLayout);
        carListingLayout.setHorizontalGroup(
            carListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carListing5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(carListing4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(carListing3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(carListing2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(carListing1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        carListingLayout.setVerticalGroup(
            carListingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carListingLayout.createSequentialGroup()
                .addComponent(carListing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carListing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carListing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carListing4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carListing5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ListingScollingPanel.setViewportView(carListing);

        LogOut.setBackground(new java.awt.Color(217, 186, 164));
        LogOut.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LogOut.setForeground(new java.awt.Color(133, 62, 52));
        LogOut.setText("Log Out");
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        EditProfile.setBackground(new java.awt.Color(217, 186, 164));
        EditProfile.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EditProfile.setForeground(new java.awt.Color(133, 62, 52));
        EditProfile.setText("Edit Profile");
        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
        });
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(NavPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ListingScollingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
            .addComponent(BookingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addComponent(NavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListingScollingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingMouseClicked

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutMouseClicked

    private void BookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CarBooking(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Booking;
    private javax.swing.JLabel Bookings14B;
    private javax.swing.JPanel BookingsPanel;
    private javax.swing.JLabel CarBrand;
    private javax.swing.JLabel CarBrand1;
    private javax.swing.JLabel CarBrand2;
    private javax.swing.JLabel CarBrand3;
    private javax.swing.JLabel CarBrand4;
    private javax.swing.JLabel CarImage;
    private javax.swing.JLabel CarImage1;
    private javax.swing.JLabel CarImage2;
    private javax.swing.JLabel CarImage3;
    private javax.swing.JLabel CarImage4;
    private javax.swing.JLabel CarModel;
    private javax.swing.JLabel CarModel1;
    private javax.swing.JLabel CarModel2;
    private javax.swing.JLabel CarModel3;
    private javax.swing.JLabel CarModel4;
    private javax.swing.JLabel CarOwner;
    private javax.swing.JLabel CarOwner1;
    private javax.swing.JLabel CarOwner2;
    private javax.swing.JLabel CarOwner3;
    private javax.swing.JLabel CarOwner4;
    private javax.swing.JLabel CarOwnerRating;
    private javax.swing.JLabel CarOwnerRating1;
    private javax.swing.JLabel CarOwnerRating2;
    private javax.swing.JLabel CarOwnerRating3;
    private javax.swing.JLabel CarOwnerRating4;
    private javax.swing.JLabel CarRating;
    private javax.swing.JLabel CarRating1;
    private javax.swing.JLabel CarRating2;
    private javax.swing.JLabel CarRating3;
    private javax.swing.JLabel CarRating4;
    private javax.swing.JLabel CarYear;
    private javax.swing.JLabel CarYear1;
    private javax.swing.JLabel CarYear2;
    private javax.swing.JLabel CarYear3;
    private javax.swing.JLabel CarYear4;
    private javax.swing.JButton Dashboard;
    private javax.swing.JLabel DateCarListed;
    private javax.swing.JLabel DateCarListed1;
    private javax.swing.JLabel DateCarListed2;
    private javax.swing.JLabel DateCarListed3;
    private javax.swing.JLabel DateCarListed4;
    private javax.swing.JButton EditProfile;
    private javax.swing.JLabel Leenda;
    private javax.swing.JScrollPane ListingScollingPanel;
    private javax.swing.JButton LogOut;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JLabel NumberOfBookings;
    private javax.swing.JLabel NumberOfBookings1;
    private javax.swing.JLabel NumberOfBookings2;
    private javax.swing.JLabel NumberOfBookings3;
    private javax.swing.JLabel NumberOfBookings4;
    private javax.swing.JLabel NumberOfComments;
    private javax.swing.JLabel NumberOfComments1;
    private javax.swing.JLabel NumberOfComments2;
    private javax.swing.JLabel NumberOfComments3;
    private javax.swing.JLabel NumberOfComments4;
    private javax.swing.JLabel TextCarBooked;
    private javax.swing.JLabel TextCarBooked1;
    private javax.swing.JLabel TextCarBooked2;
    private javax.swing.JLabel TextCarBooked3;
    private javax.swing.JLabel TextCarBooked4;
    private javax.swing.JLabel TextCarComments;
    private javax.swing.JLabel TextCarComments1;
    private javax.swing.JLabel TextCarComments2;
    private javax.swing.JLabel TextCarComments3;
    private javax.swing.JLabel TextCarComments4;
    private javax.swing.JLabel TextCarDateListed;
    private javax.swing.JLabel TextCarDateListed1;
    private javax.swing.JLabel TextCarDateListed2;
    private javax.swing.JLabel TextCarDateListed3;
    private javax.swing.JLabel TextCarDateListed4;
    private javax.swing.JLabel TextCarRatings;
    private javax.swing.JLabel TextCarRatings1;
    private javax.swing.JLabel TextCarRatings2;
    private javax.swing.JLabel TextCarRatings3;
    private javax.swing.JLabel TextCarRatings4;
    private javax.swing.JLabel TextOwnerRating;
    private javax.swing.JLabel TextOwnerRating1;
    private javax.swing.JLabel TextOwnerRating2;
    private javax.swing.JLabel TextOwnerRating3;
    private javax.swing.JLabel TextOwnerRating4;
    private javax.swing.JPanel carImageBox;
    private javax.swing.JPanel carImageBox1;
    private javax.swing.JPanel carImageBox2;
    private javax.swing.JPanel carImageBox3;
    private javax.swing.JPanel carImageBox4;
    private javax.swing.JPanel carListing;
    private javax.swing.JPanel carListing1;
    private javax.swing.JPanel carListing2;
    private javax.swing.JPanel carListing3;
    private javax.swing.JPanel carListing4;
    private javax.swing.JPanel carListing5;
    // End of variables declaration//GEN-END:variables
}
