/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package leendauserdashboard;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import auth.LoginPage;
import models.User;
import storage.StorageFunctions;

/**
 *
 * @author Jaden
 */
public class CustomerDashboard extends javax.swing.JFrame {
    public User user;
    /**
     * Creates new form UserDashboard
     */
    public CustomerDashboard(User user) {
    try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();  // Handle any exceptions
        }

        this.user = user;
        initComponents();
        this.setVisible(true);

        try {
            // spendings
            double totalSpendingsFromFile = StorageFunctions.getCustomerSpening(user.getEmail());
            spendings.setText("NAD "+ totalSpendingsFromFile);

            // completedBookings
            int totalBookings = StorageFunctions.countBookingsByUserEmail(user.getEmail());
            completedBookings.setText(" "+ totalBookings);

            // pendingApproval
            int totalDaysRented = StorageFunctions.countTotalDaysRented(user.getEmail());
            pendingApproval.setText(" "+ totalDaysRented);

            // totalBookingsText

            int totalBookingsFromFile = StorageFunctions.countTotalBookings(user.getEmail());
            totalBookingsText.setText(" "+ totalBookingsFromFile);

            // canceledBookings
            int  totalCanceledBookings = StorageFunctions.countCanceledBookings(user.getEmail());
            canceledBookings.setText(" "+ totalCanceledBookings);  
        } catch (Exception e) {
            // TODO: handle exception
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        DashboardPanel = new javax.swing.JPanel();
        Dashboard14B = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        userIcon = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        userType = new javax.swing.JLabel();
        TotalBookings = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalBookingsText = new javax.swing.JLabel();
        totalBookings = new javax.swing.JLabel();
        Search = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchRandomFraises = new javax.swing.JLabel();
        spendingsPanel = new javax.swing.JPanel();
        spendingsIcon = new javax.swing.JLabel();
        spendingsText = new javax.swing.JLabel();
        spendings = new javax.swing.JLabel();
        pendingApprovalPanel = new javax.swing.JPanel();
        pendingApprovalIcon = new javax.swing.JLabel();
        pendingApprovalText = new javax.swing.JLabel();
        pendingApproval = new javax.swing.JLabel();
        completedBookingsPanel = new javax.swing.JPanel();
        completedBookingsIcon = new javax.swing.JLabel();
        completedBookingsText = new javax.swing.JLabel();
        completedBookings = new javax.swing.JLabel();
        canceledBookingPanel = new javax.swing.JPanel();
        canceledBookingIcon = new javax.swing.JLabel();
        canceledBookingText = new javax.swing.JLabel();
        canceledBookings = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        EditProfile = new javax.swing.JButton();
        NavPanel = new javax.swing.JPanel();
        Leenda = new javax.swing.JLabel();
        Booking = new javax.swing.JButton();
        Dashboard = new javax.swing.JButton();
        ViewCar = new javax.swing.JButton();
        firstName.setText(user.getFirstName());
        lastName.setText(user.getLastName());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(237, 223, 205));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        Background.setBackground(new java.awt.Color(237, 223, 205));

        DashboardPanel.setBackground(new java.awt.Color(237, 223, 205));
        DashboardPanel.setForeground(new java.awt.Color(237, 223, 205));

        Dashboard14B.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Dashboard14B.setForeground(new java.awt.Color(133, 62, 52));
        Dashboard14B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard14B.setText("Dashboard");

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard14B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dashboard14B)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        UserPanel.setBackground(new java.awt.Color(217, 186, 164));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-88 (3).png"))); // NOI18N

        firstName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        firstName.setForeground(new java.awt.Color(133, 62, 52));
        // firstName.setText("Jaden");
        firstName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lastName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lastName.setForeground(new java.awt.Color(133, 62, 52));
        // lastName.setText("Smith");
        lastName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        userType.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        userType.setForeground(new java.awt.Color(133, 62, 52));
        userType.setText("Customer");
        userType.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
        UserPanel.setLayout(UserPanelLayout);
        UserPanelLayout.setHorizontalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserPanelLayout.createSequentialGroup()
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userType)
                .addGap(24, 24, 24))
        );
        UserPanelLayout.setVerticalGroup(
            UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserPanelLayout.createSequentialGroup()
                .addGroup(UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UserPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TotalBookings.setBackground(new java.awt.Color(217, 186, 164));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-books-88 (1).png"))); // NOI18N

        totalBookingsText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        totalBookingsText.setForeground(new java.awt.Color(133, 62, 52));
        totalBookingsText.setText("Total Bookings");
        totalBookingsText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        totalBookings.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        totalBookings.setForeground(new java.awt.Color(133, 62, 52));
        totalBookings.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        //totalBookings.setText("81");
        totalBookings.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout TotalBookingsLayout = new javax.swing.GroupLayout(TotalBookings);
        TotalBookings.setLayout(TotalBookingsLayout);
        TotalBookingsLayout.setHorizontalGroup(
            TotalBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalBookingsLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalBookingsText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalBookings)
                .addGap(23, 23, 23))
        );
        TotalBookingsLayout.setVerticalGroup(
            TotalBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalBookingsLayout.createSequentialGroup()
                .addGroup(TotalBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalBookingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(TotalBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalBookingsText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Search.setBackground(new java.awt.Color(217, 186, 164));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 62, 52));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Leenda");

        searchRandomFraises.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        searchRandomFraises.setForeground(new java.awt.Color(133, 62, 52));
        searchRandomFraises.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchRandomFraises.setText("Check out what we got, your ride is just a tab bar away!");
        searchRandomFraises.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout SearchLayout = new javax.swing.GroupLayout(Search);
        Search.setLayout(SearchLayout);
        SearchLayout.setHorizontalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchRandomFraises, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216))
        );
        SearchLayout.setVerticalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchRandomFraises, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(75, 75, 75))
        );

        spendingsPanel.setBackground(new java.awt.Color(217, 186, 164));

        spendingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-payment-history-88.png"))); // NOI18N

        spendingsText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        spendingsText.setForeground(new java.awt.Color(133, 62, 52));
        spendingsText.setText("Spendings");
        spendingsText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        spendings.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        spendings.setForeground(new java.awt.Color(133, 62, 52));
        //spendings.setText("NAD 69420");
        spendings.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout spendingsPanelLayout = new javax.swing.GroupLayout(spendingsPanel);
        spendingsPanel.setLayout(spendingsPanelLayout);
        spendingsPanelLayout.setHorizontalGroup(
            spendingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spendingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spendingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(spendingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spendingsText)
                    .addComponent(spendings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        spendingsPanelLayout.setVerticalGroup(
            spendingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spendingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spendingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spendingsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(spendingsPanelLayout.createSequentialGroup()
                        .addComponent(spendingsText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spendings, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pendingApprovalPanel.setBackground(new java.awt.Color(217, 186, 164));

        pendingApprovalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-clock-88 (1).png"))); // NOI18N

        pendingApprovalText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        pendingApprovalText.setForeground(new java.awt.Color(133, 62, 52));
        pendingApprovalText.setText("Pending Approval");
        pendingApprovalText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        pendingApproval.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        pendingApproval.setForeground(new java.awt.Color(133, 62, 52));
        //pendingApproval.setText("36");
        pendingApproval.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pendingApprovalPanelLayout = new javax.swing.GroupLayout(pendingApprovalPanel);
        pendingApprovalPanel.setLayout(pendingApprovalPanelLayout);
        pendingApprovalPanelLayout.setHorizontalGroup(
            pendingApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingApprovalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pendingApprovalIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pendingApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pendingApprovalText)
                    .addComponent(pendingApproval))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pendingApprovalPanelLayout.setVerticalGroup(
            pendingApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingApprovalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pendingApprovalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pendingApprovalIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pendingApprovalPanelLayout.createSequentialGroup()
                        .addComponent(pendingApprovalText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pendingApproval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        completedBookingsPanel.setBackground(new java.awt.Color(217, 186, 164));

        completedBookingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-order-completed-88.png"))); // NOI18N

        completedBookingsText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        completedBookingsText.setForeground(new java.awt.Color(133, 62, 52));
        completedBookingsText.setText("Completed Bookings");
        completedBookingsText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        completedBookings.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        completedBookings.setForeground(new java.awt.Color(133, 62, 52));
        //completedBookings.setText("64");
        completedBookings.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout completedBookingsPanelLayout = new javax.swing.GroupLayout(completedBookingsPanel);
        completedBookingsPanel.setLayout(completedBookingsPanelLayout);
        completedBookingsPanelLayout.setHorizontalGroup(
            completedBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedBookingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(completedBookingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(completedBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completedBookingsText)
                    .addComponent(completedBookings))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        completedBookingsPanelLayout.setVerticalGroup(
            completedBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedBookingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(completedBookingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completedBookingsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(completedBookingsPanelLayout.createSequentialGroup()
                        .addComponent(completedBookingsText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(completedBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        canceledBookingPanel.setBackground(new java.awt.Color(217, 186, 164));

        canceledBookingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-cancel-subscription-88.png"))); // NOI18N

        canceledBookingText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        canceledBookingText.setForeground(new java.awt.Color(133, 62, 52));
        canceledBookingText.setText("Canceled Bookings");
        canceledBookingText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        canceledBookings.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        canceledBookings.setForeground(new java.awt.Color(133, 62, 52));
        //canceledBookings.setText("1");
        canceledBookings.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout canceledBookingPanelLayout = new javax.swing.GroupLayout(canceledBookingPanel);
        canceledBookingPanel.setLayout(canceledBookingPanelLayout);
        canceledBookingPanelLayout.setHorizontalGroup(
            canceledBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canceledBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canceledBookingIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(canceledBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canceledBookingText)
                    .addComponent(canceledBookings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        canceledBookingPanelLayout.setVerticalGroup(
            canceledBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canceledBookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(canceledBookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canceledBookingIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(canceledBookingPanelLayout.createSequentialGroup()
                        .addComponent(canceledBookingText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(canceledBookings)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        LogOut.setBackground(new java.awt.Color(217, 186, 164));
        LogOut.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LogOut.setForeground(new java.awt.Color(133, 62, 52));
        LogOut.setText("Log Out");
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        EditProfile.setBackground(new java.awt.Color(217, 186, 164));
        EditProfile.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        EditProfile.setForeground(new java.awt.Color(133, 62, 52));
        EditProfile.setText("Edit Profile");
        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
        });
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });

        NavPanel.setBackground(new java.awt.Color(217, 186, 164));
        NavPanel.setForeground(new java.awt.Color(217, 186, 164));

        Leenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Leenda.setForeground(new java.awt.Color(133, 62, 52));
        Leenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Leenda.setText("Leenda");

        Booking.setBackground(new java.awt.Color(237, 223, 205));
        Booking.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Booking.setForeground(new java.awt.Color(133, 62, 52));
        Booking.setText("Bookings");
        Booking.setToolTipText("Check out the catalog, something might catch your eye.");
        Booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingMouseClicked(evt);
            }
        });

        Dashboard.setBackground(new java.awt.Color(237, 223, 205));
        Dashboard.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(133, 62, 52));
        Dashboard.setText("Dashboard");
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
        });
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        ViewCar.setBackground(new java.awt.Color(237, 223, 205));
        ViewCar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ViewCar.setForeground(new java.awt.Color(133, 62, 52));
        ViewCar.setText("View Car");
        ViewCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCarMouseClicked(evt);
            }
        });
        ViewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavPanelLayout = new javax.swing.GroupLayout(NavPanel);
        NavPanel.setLayout(NavPanelLayout);
        NavPanelLayout.setHorizontalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Leenda, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewCar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Booking, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavPanelLayout.setVerticalGroup(
            NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavPanelLayout.createSequentialGroup()
                .addGroup(NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Leenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TotalBookings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NavPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(EditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pendingApprovalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(completedBookingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spendingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(canceledBookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addComponent(NavPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalBookings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pendingApprovalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spendingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completedBookingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canceledBookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardMouseClicked

    private void BookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingMouseClicked
        this.dispose();
        new Bookings(user);
    }//GEN-LAST:event_BookingMouseClicked

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditProfileMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        new LoginPage();
    }//GEN-LAST:event_LogOutMouseClicked

    private void ViewCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCarMouseClicked
        this.dispose();
        new ViewCars(user);
    }//GEN-LAST:event_ViewCarMouseClicked

    private void ViewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CustomerDashboard(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Booking;
    private javax.swing.JButton Dashboard;
    private javax.swing.JLabel Dashboard14B;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JButton EditProfile;
    private javax.swing.JLabel Leenda;
    private javax.swing.JButton LogOut;
    private javax.swing.JPanel NavPanel;
    private javax.swing.JPanel Search;
    private javax.swing.JPanel TotalBookings;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton ViewCar;
    private javax.swing.JLabel canceledBookingIcon;
    private javax.swing.JPanel canceledBookingPanel;
    private javax.swing.JLabel canceledBookingText;
    private javax.swing.JLabel canceledBookings;
    private javax.swing.JLabel completedBookings;
    private javax.swing.JLabel completedBookingsIcon;
    private javax.swing.JPanel completedBookingsPanel;
    private javax.swing.JLabel completedBookingsText;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel pendingApproval;
    private javax.swing.JLabel pendingApprovalIcon;
    private javax.swing.JPanel pendingApprovalPanel;
    private javax.swing.JLabel pendingApprovalText;
    private javax.swing.JLabel searchRandomFraises;
    private javax.swing.JLabel spendings;
    private javax.swing.JLabel spendingsIcon;
    private javax.swing.JPanel spendingsPanel;
    private javax.swing.JLabel spendingsText;
    private javax.swing.JLabel totalBookings;
    private javax.swing.JLabel totalBookingsText;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userType;
    // End of variables declaration//GEN-END:variables
}
