package auth;

import javax.swing.JOptionPane;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author euric
 */
public class SignUpPage extends javax.swing.JFrame {

        /**
         * Creates new form SignUpPage
         */
        public SignUpPage() {
                initComponents();
                this.setTitle("Sign up page");
                this.setLocationRelativeTo(null); // Center the form on the screen
                this.setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pnlMain = new javax.swing.JPanel();
                lblSignUp = new javax.swing.JLabel();
                lblSelectTheRole = new javax.swing.JLabel();
                cboRole = new javax.swing.JComboBox<>();
                lblFirstName = new javax.swing.JLabel();
                txtFirstName = new javax.swing.JTextField();
                lblLastName = new javax.swing.JLabel();
                txtLastName = new javax.swing.JTextField();
                txtEmail = new javax.swing.JTextField();
                lblEmail = new javax.swing.JLabel();
                lblPhoneNumber = new javax.swing.JLabel();
                txtPhoneNumber = new javax.swing.JTextField();
                lblDriverLicense = new javax.swing.JLabel();
                txtDriverLicense = new javax.swing.JTextField();
                txtPassword = new javax.swing.JPasswordField();
                lblPassword = new javax.swing.JLabel();
                lblConfirmPassword = new javax.swing.JLabel();
                txtConfirmPassword = new javax.swing.JPasswordField();
                btnSignUp = new javax.swing.JToggleButton();
                btnLogin = new javax.swing.JToggleButton();
                lblLeenda = new javax.swing.JLabel();
                chkShowPassword = new javax.swing.JCheckBox();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                setResizable(false);

                pnlMain.setBackground(new java.awt.Color(237, 223, 205));
                pnlMain.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

                lblSignUp.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
                lblSignUp.setText("Sign Up");

                lblSelectTheRole.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblSelectTheRole.setText("Select the role");

                cboRole.setBackground(new java.awt.Color(217, 186, 164));
                cboRole.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                cboRole.setForeground(new java.awt.Color(133, 62, 52));
                cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Admin", "Car owner", "Customer" }));
                cboRole.setOpaque(true);

                lblFirstName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblFirstName.setText("First name");

                txtFirstName.setBackground(new java.awt.Color(217, 186, 164));
                txtFirstName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

                lblLastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblLastName.setText("Last name");

                txtLastName.setBackground(new java.awt.Color(217, 186, 164));
                txtLastName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

                txtEmail.setBackground(new java.awt.Color(217, 186, 164));
                txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

                lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblEmail.setText("Email");

                lblPhoneNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblPhoneNumber.setText("Phone number");

                txtPhoneNumber.setBackground(new java.awt.Color(217, 186, 164));
                txtPhoneNumber.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

                lblDriverLicense.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblDriverLicense.setText("Driver license");

                txtDriverLicense.setBackground(new java.awt.Color(217, 186, 164));
                txtDriverLicense.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

                txtPassword.setBackground(new java.awt.Color(217, 186, 164));
                txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

                lblPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblPassword.setText("Password");

                lblConfirmPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                lblConfirmPassword.setText("Confirm password");

                txtConfirmPassword.setBackground(new java.awt.Color(217, 186, 164));
                txtConfirmPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

                btnSignUp.setBackground(new java.awt.Color(133, 62, 52));
                btnSignUp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                btnSignUp.setForeground(new java.awt.Color(237, 223, 205));
                btnSignUp.setText("Sign Up");
                btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnSignUpOnClick(evt);
                        }
                });

                btnLogin.setBackground(new java.awt.Color(237, 223, 205));
                btnLogin.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                btnLogin.setForeground(new java.awt.Color(133, 62, 52));
                btnLogin.setText("Login");
                btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btnLoginOnClick(evt);
                        }
                });

                lblLeenda.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                lblLeenda.setText("Leenda");

                chkShowPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
                chkShowPassword.setForeground(new java.awt.Color(133, 62, 52));
                chkShowPassword.setText("Show password");
                chkShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                chkShowPassword.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                chkShowPasswordOnClick(evt);
                        }
                });

                javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
                pnlMain.setLayout(pnlMainLayout);
                pnlMainLayout.setHorizontalGroup(
                                pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlMainLayout.createSequentialGroup()
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(pnlMainLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(pnlMainLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addComponent(txtLastName,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                169,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                pnlMainLayout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addGap(2, 2, 2)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                lblLastName)))
                                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addContainerGap()
                                                                                                                                                                                .addComponent(txtFirstName,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                169,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                pnlMainLayout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addGap(110, 110,
                                                                                                                                                                                                                110)
                                                                                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                lblFirstName)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                lblSelectTheRole)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                lblSignUp)
                                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                                cboRole,
                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                167,
                                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addComponent(txtEmail,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                169,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                pnlMainLayout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addGap(2, 2, 2)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                lblEmail))))
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(lblPassword)
                                                                                                                                                .addComponent(txtPhoneNumber,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                169,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(lblPhoneNumber)
                                                                                                                                                .addComponent(lblDriverLicense)
                                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addComponent(chkShowPassword)
                                                                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                                false)
                                                                                                                                                                                .addComponent(txtDriverLicense)
                                                                                                                                                                                .addComponent(txtPassword)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                txtConfirmPassword,
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                169,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                lblConfirmPassword,
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)))))
                                                                                                                .addGroup(pnlMainLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(btnSignUp,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                169,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(btnLogin,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                169,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGap(0, 117, Short.MAX_VALUE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                pnlMainLayout.createSequentialGroup()
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                                .addComponent(lblLeenda)))
                                                                .addContainerGap()));
                pnlMainLayout.setVerticalGroup(
                                pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlMainLayout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(lblSignUp)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblSelectTheRole)
                                                                                .addComponent(lblPhoneNumber))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(cboRole,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtPhoneNumber,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblFirstName)
                                                                                .addComponent(lblDriverLicense))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtFirstName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtDriverLicense,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblLastName)
                                                                                .addComponent(lblPassword))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtLastName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtPassword,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(21, 21, 21)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblEmail)
                                                                                .addComponent(lblConfirmPassword))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtEmail,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtConfirmPassword,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(chkShowPassword)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlMainLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnSignUp)
                                                                                .addComponent(btnLogin))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                28,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(lblLeenda)
                                                                .addContainerGap()));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnLoginOnClick(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnLoginOnClick
                this.dispose();
                new LoginPage();
        }// GEN-LAST:event_btnLoginOnClick

        private void chkShowPasswordOnClick(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkShowPasswordOnClick
                // TODO add your handling code here:
                if (chkShowPassword.isSelected()) {
                        txtPassword.setEchoChar('\u0000');
                        txtConfirmPassword.setEchoChar('\u0000');
                        chkShowPassword.setText("Hide password");
                } else {
                        txtPassword.setEchoChar('*');
                        txtConfirmPassword.setEchoChar('*');
                        chkShowPassword.setText("Show password");
                }
        }// GEN-LAST:event_chkShowPasswordOnClick

        private void btnSignUpOnClick(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnSignUpOnClick
                // Regular expressions
                String nameRegex = "^(?!.*\\s)(!?[A-Z][a-zA-Z]*)$"; // First letter uppercase, then letters or '!'
                String emailRegex = "^[\\w-\\.]+@[\\w-]+\\.[a-z]{2,4}$"; // Basic email validation
                String phoneRegex = "^\\+\\d{1,4}\\d+$"; // Phone number starts with + followed by digits
                String passwordRegex = "^(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"; // Password rules
                                                                                                      // (no spaces)

                // Get input values
                String firstName = txtFirstName.getText().trim();
                String lastName = txtLastName.getText().trim();
                String email = txtEmail.getText().trim();
                String phoneNumber = txtPhoneNumber.getText().trim();
                char[] passwordChars = txtPassword.getPassword();
                String password = new String(passwordChars).trim();
                char[] confirmPasswordChars = txtConfirmPassword.getPassword();
                String confirmPassword = new String(confirmPasswordChars).trim();
                final String STATUS = "pending";

                // Validation
                if (!firstName.matches(nameRegex)) {
                        JOptionPane.showMessageDialog(this,
                                        "First name is invalid. \nOnly letters and '!' are allowed.",
                                        "Invalid First Name", JOptionPane.ERROR_MESSAGE);
                } else if (!lastName.matches(nameRegex)) {
                        JOptionPane.showMessageDialog(this, "Last name is invalid. \nOnly letters and '!' are allowed.",
                                        "Invalid Last Name", JOptionPane.ERROR_MESSAGE);
                } else if (!email.matches(emailRegex)) {
                        JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Invalid Email",
                                        JOptionPane.ERROR_MESSAGE);
                } else if (!phoneNumber.matches(phoneRegex)) {
                        JOptionPane.showMessageDialog(this,
                                        "Phone number must start with +country code \nand contain only numbers.",
                                        "Invalid Phone Number",
                                        JOptionPane.ERROR_MESSAGE);
                } else if (!password.matches(passwordRegex)) {
                        JOptionPane.showMessageDialog(this,
                                        "Password must have at least one uppercase letter, \none number, one special character, and no spaces.",
                                        "Invalid Password", JOptionPane.ERROR_MESSAGE);
                } else if (!password.equals(confirmPassword)) {
                        JOptionPane.showMessageDialog(this, "Passwords do not match.", "Password Mismatch",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        // All validations passed

                        // Check if the email already exists in the file
                        if (AuthFunctions.doesEmailExist(email)) {
                                JOptionPane.showMessageDialog(this,
                                                "Email is already in use. Please choose another one.",
                                                "Email Exists", JOptionPane.ERROR_MESSAGE);
                        } else {
                                // Get selected user role from the combo box (e.g., Car owner, Customer, Admin)
                                String userRole = cboRole.getSelectedItem().toString();
                                String driverLicense = txtDriverLicense.getText().trim().toUpperCase(); // Optional
                                                                                                        // field

                                // Check if the user role is not "Admin" and driver license is empty
                                if (!userRole.equals("Admin") && driverLicense.isEmpty()) {
                                        JOptionPane.showMessageDialog(this,
                                                        "Driver's license is required for non-admin users.",
                                                        "Missing Driver's License", JOptionPane.ERROR_MESSAGE);
                                } else {
                                        // Create a new line for the CSV
                                        String newUser = String.format("%s,%s,%s,%s,%s,%s,%s,%s,%s",
                                                        email,
                                                        AuthFunctions.hash(password),
                                                        phoneNumber,
                                                        userRole,
                                                        firstName,
                                                        lastName,
                                                        driverLicense.isEmpty() ? "" : driverLicense,
                                                        AuthFunctions.generateUserID(), STATUS); // A method to generate
                                                                                                 // a unique userID
                                        // Append the new user to the CSV file
                                        try (BufferedWriter bw = new BufferedWriter(
                                                        new FileWriter("src\\storage\\userDetails.csv", true))) {
                                                bw.write(newUser);
                                                bw.newLine(); // Add a newline after the user details
                                                JOptionPane.showMessageDialog(this, "Sign-up successful!");

                                                // Close the sign-up form and open the login page
                                                this.dispose();
                                                new LoginPage();
                                        } catch (IOException e) {
                                                JOptionPane.showMessageDialog(this,
                                                                "Error writing to file: " + e.getMessage(),
                                                                "File Write Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                }
                        }
                }
        }// GEN-LAST:event_btnSignUpOnClick

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new SignUpPage().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JToggleButton btnLogin;
        private javax.swing.JToggleButton btnSignUp;
        private javax.swing.JComboBox<String> cboRole;
        private javax.swing.JCheckBox chkShowPassword;
        private javax.swing.JLabel lblConfirmPassword;
        private javax.swing.JLabel lblDriverLicense;
        private javax.swing.JLabel lblEmail;
        private javax.swing.JLabel lblFirstName;
        private javax.swing.JLabel lblLastName;
        private javax.swing.JLabel lblLeenda;
        private javax.swing.JLabel lblPassword;
        private javax.swing.JLabel lblPhoneNumber;
        private javax.swing.JLabel lblSelectTheRole;
        private javax.swing.JLabel lblSignUp;
        private javax.swing.JPanel pnlMain;
        private javax.swing.JPasswordField txtConfirmPassword;
        private javax.swing.JTextField txtDriverLicense;
        private javax.swing.JTextField txtEmail;
        private javax.swing.JTextField txtFirstName;
        private javax.swing.JTextField txtLastName;
        private javax.swing.JPasswordField txtPassword;
        private javax.swing.JTextField txtPhoneNumber;
        // End of variables declaration//GEN-END:variables
}
