package auth;

import javax.swing.*;

public class SplashScreen extends javax.swing.JWindow  {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        // Set Nimbus look and feel
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();  // Handle any exceptions
        }
        this.setVisible(true);//allowing the display of the splash screen
        initComponents();
        this.setLocationRelativeTo(null);//centralising the slpash screen
        
        int count = 0; //initialising the counter
        
        while(count<=100){
            progressBar.setValue(count);//allowing the progressBar to iterate from 0 to 100
            
            if(count % 2 == 0)
                lblLoading.setVisible(false);
            else
                lblLoading.setVisible(true);
            // Optionally add a delay to keep it visible
            try {
                Thread.sleep(30); // Show for 3 seconds
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            count++;
        }
        
        this.dispose(); // Close the splash screen
        
         new LoginPage().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSplash = new javax.swing.JPanel();
        locationIcon = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblLeenda = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();

        setBackground(new java.awt.Color(133, 62, 52));
        setForeground(new java.awt.Color(255, 255, 255));
        setName("splashScreen"); // NOI18N

        panelSplash.setBackground(new java.awt.Color(133, 62, 52));
        panelSplash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSplash.setForeground(new java.awt.Color(255, 255, 255));
        panelSplash.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        progressBar.setBackground(new java.awt.Color(237, 223, 205));
        progressBar.setForeground(new java.awt.Color(0, 0, 0));
        progressBar.setBorder(null);
        progressBar.setBorderPainted(false);
        progressBar.setOpaque(true);
        progressBar.setStringPainted(true);

        lblLeenda.setBackground(new java.awt.Color(237, 223, 205));
        lblLeenda.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblLeenda.setForeground(new java.awt.Color(255, 255, 255));
        lblLeenda.setText("Leenda");

        lblVersion.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setText("Version 1.0");

        lblLoading.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        lblLoading.setForeground(new java.awt.Color(255, 255, 255));
        lblLoading.setText("Loading...");

        lblLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/location.png"))); // NOI18N

        javax.swing.GroupLayout panelSplashLayout = new javax.swing.GroupLayout(panelSplash);
        panelSplash.setLayout(panelSplashLayout);
        panelSplashLayout.setHorizontalGroup(
            panelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSplashLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelSplashLayout.createSequentialGroup()
                .addGroup(panelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSplashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLeenda))
                    .addGroup(panelSplashLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(locationIcon))
                    .addGroup(panelSplashLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(panelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSplashLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(lblLoading))
                            .addGroup(panelSplashLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblLocation)))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        panelSplashLayout.setVerticalGroup(
            panelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSplashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLeenda)
                .addGap(62, 62, 62)
                .addComponent(lblLocation)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locationIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(lblVersion))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSplash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSplash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("splashScreen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Create and display the splash screen
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen();
                // After the splash screen, you can start your main application
                // For example:
                // new MainApplication().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLeenda;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JLabel locationIcon;
    private javax.swing.JPanel panelSplash;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}

/**
 *
 * @author: <edande - 223134902/>
 */